// Budget.proto defines messages for budget information from cost management services.
// This file contains the data structures for representing spending limits, thresholds,
// and budget status across different cloud providers.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: pulumicost/v1/budget.proto

package pbc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BudgetPeriod defines the time interval for budget calculations.
type BudgetPeriod int32

const (
	BudgetPeriod_BUDGET_PERIOD_UNSPECIFIED BudgetPeriod = 0 // Invalid/unset
	BudgetPeriod_BUDGET_PERIOD_DAILY       BudgetPeriod = 1 // Daily budget cycle
	BudgetPeriod_BUDGET_PERIOD_WEEKLY      BudgetPeriod = 2 // Weekly budget cycle
	BudgetPeriod_BUDGET_PERIOD_MONTHLY     BudgetPeriod = 3 // Monthly budget cycle
	BudgetPeriod_BUDGET_PERIOD_QUARTERLY   BudgetPeriod = 4 // Quarterly budget cycle
	BudgetPeriod_BUDGET_PERIOD_ANNUALLY    BudgetPeriod = 5 // Annual budget cycle
)

// Enum value maps for BudgetPeriod.
var (
	BudgetPeriod_name = map[int32]string{
		0: "BUDGET_PERIOD_UNSPECIFIED",
		1: "BUDGET_PERIOD_DAILY",
		2: "BUDGET_PERIOD_WEEKLY",
		3: "BUDGET_PERIOD_MONTHLY",
		4: "BUDGET_PERIOD_QUARTERLY",
		5: "BUDGET_PERIOD_ANNUALLY",
	}
	BudgetPeriod_value = map[string]int32{
		"BUDGET_PERIOD_UNSPECIFIED": 0,
		"BUDGET_PERIOD_DAILY":       1,
		"BUDGET_PERIOD_WEEKLY":      2,
		"BUDGET_PERIOD_MONTHLY":     3,
		"BUDGET_PERIOD_QUARTERLY":   4,
		"BUDGET_PERIOD_ANNUALLY":    5,
	}
)

func (x BudgetPeriod) Enum() *BudgetPeriod {
	p := new(BudgetPeriod)
	*p = x
	return p
}

func (x BudgetPeriod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BudgetPeriod) Descriptor() protoreflect.EnumDescriptor {
	return file_pulumicost_v1_budget_proto_enumTypes[0].Descriptor()
}

func (BudgetPeriod) Type() protoreflect.EnumType {
	return &file_pulumicost_v1_budget_proto_enumTypes[0]
}

func (x BudgetPeriod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BudgetPeriod.Descriptor instead.
func (BudgetPeriod) EnumDescriptor() ([]byte, []int) {
	return file_pulumicost_v1_budget_proto_rawDescGZIP(), []int{0}
}

// ThresholdType specifies whether the threshold applies to actual or forecasted spending.
type ThresholdType int32

const (
	ThresholdType_THRESHOLD_TYPE_UNSPECIFIED ThresholdType = 0 // Invalid/unset
	ThresholdType_THRESHOLD_TYPE_ACTUAL      ThresholdType = 1 // Based on actual spending
	ThresholdType_THRESHOLD_TYPE_FORECASTED  ThresholdType = 2 // Based on forecasted spending
)

// Enum value maps for ThresholdType.
var (
	ThresholdType_name = map[int32]string{
		0: "THRESHOLD_TYPE_UNSPECIFIED",
		1: "THRESHOLD_TYPE_ACTUAL",
		2: "THRESHOLD_TYPE_FORECASTED",
	}
	ThresholdType_value = map[string]int32{
		"THRESHOLD_TYPE_UNSPECIFIED": 0,
		"THRESHOLD_TYPE_ACTUAL":      1,
		"THRESHOLD_TYPE_FORECASTED":  2,
	}
)

func (x ThresholdType) Enum() *ThresholdType {
	p := new(ThresholdType)
	*p = x
	return p
}

func (x ThresholdType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThresholdType) Descriptor() protoreflect.EnumDescriptor {
	return file_pulumicost_v1_budget_proto_enumTypes[1].Descriptor()
}

func (ThresholdType) Type() protoreflect.EnumType {
	return &file_pulumicost_v1_budget_proto_enumTypes[1]
}

func (x ThresholdType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThresholdType.Descriptor instead.
func (ThresholdType) EnumDescriptor() ([]byte, []int) {
	return file_pulumicost_v1_budget_proto_rawDescGZIP(), []int{1}
}

// BudgetHealthStatus represents the overall health state of a budget.
type BudgetHealthStatus int32

const (
	BudgetHealthStatus_BUDGET_HEALTH_STATUS_UNSPECIFIED BudgetHealthStatus = 0 // Invalid/unset
	BudgetHealthStatus_BUDGET_HEALTH_STATUS_OK          BudgetHealthStatus = 1 // Within normal thresholds
	BudgetHealthStatus_BUDGET_HEALTH_STATUS_WARNING     BudgetHealthStatus = 2 // Approaching limits
	BudgetHealthStatus_BUDGET_HEALTH_STATUS_CRITICAL    BudgetHealthStatus = 3 // Near or at limits
	BudgetHealthStatus_BUDGET_HEALTH_STATUS_EXCEEDED    BudgetHealthStatus = 4 // Over budget
)

// Enum value maps for BudgetHealthStatus.
var (
	BudgetHealthStatus_name = map[int32]string{
		0: "BUDGET_HEALTH_STATUS_UNSPECIFIED",
		1: "BUDGET_HEALTH_STATUS_OK",
		2: "BUDGET_HEALTH_STATUS_WARNING",
		3: "BUDGET_HEALTH_STATUS_CRITICAL",
		4: "BUDGET_HEALTH_STATUS_EXCEEDED",
	}
	BudgetHealthStatus_value = map[string]int32{
		"BUDGET_HEALTH_STATUS_UNSPECIFIED": 0,
		"BUDGET_HEALTH_STATUS_OK":          1,
		"BUDGET_HEALTH_STATUS_WARNING":     2,
		"BUDGET_HEALTH_STATUS_CRITICAL":    3,
		"BUDGET_HEALTH_STATUS_EXCEEDED":    4,
	}
)

func (x BudgetHealthStatus) Enum() *BudgetHealthStatus {
	p := new(BudgetHealthStatus)
	*p = x
	return p
}

func (x BudgetHealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BudgetHealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pulumicost_v1_budget_proto_enumTypes[2].Descriptor()
}

func (BudgetHealthStatus) Type() protoreflect.EnumType {
	return &file_pulumicost_v1_budget_proto_enumTypes[2]
}

func (x BudgetHealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BudgetHealthStatus.Descriptor instead.
func (BudgetHealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_pulumicost_v1_budget_proto_rawDescGZIP(), []int{2}
}

// Budget represents a spending limit with alert thresholds from cloud cost management services.
// This unified structure supports budgets from AWS, GCP, Azure, Kubecost, and other providers.
type Budget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                        // Unique identifier for the budget (required, non-empty)
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                                    // Human-readable budget name (required, non-empty)
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`                                                                                // Provider identifier (e.g., "aws-budgets", "gcp-billing", "kubecost")
	Amount        *BudgetAmount          `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`                                                                                // Monetary limit and currency (required)
	Period        BudgetPeriod           `protobuf:"varint,5,opt,name=period,proto3,enum=pulumicost.v1.BudgetPeriod" json:"period,omitempty"`                                               // Time interval for budget calculations (required)
	Filter        *BudgetFilter          `protobuf:"bytes,6,opt,name=filter,proto3" json:"filter,omitempty"`                                                                                // Optional scope restrictions (provider, region, tags)
	Thresholds    []*BudgetThreshold     `protobuf:"bytes,7,rep,name=thresholds,proto3" json:"thresholds,omitempty"`                                                                        // Alert points with percentages (optional)
	Status        *BudgetStatus          `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`                                                                                // Current spending state (optional, populated when include_status=true)
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                                                         // Budget creation time (optional)
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                                                        // Last budget modification time (optional)
	Metadata      map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Provider-specific additional data (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Budget) Reset() {
	*x = Budget{}
	mi := &file_pulumicost_v1_budget_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Budget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Budget) ProtoMessage() {}

func (x *Budget) ProtoReflect() protoreflect.Message {
	mi := &file_pulumicost_v1_budget_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Budget.ProtoReflect.Descriptor instead.
func (*Budget) Descriptor() ([]byte, []int) {
	return file_pulumicost_v1_budget_proto_rawDescGZIP(), []int{0}
}

func (x *Budget) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Budget) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Budget) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Budget) GetAmount() *BudgetAmount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Budget) GetPeriod() BudgetPeriod {
	if x != nil {
		return x.Period
	}
	return BudgetPeriod_BUDGET_PERIOD_UNSPECIFIED
}

func (x *Budget) GetFilter() *BudgetFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *Budget) GetThresholds() []*BudgetThreshold {
	if x != nil {
		return x.Thresholds
	}
	return nil
}

func (x *Budget) GetStatus() *BudgetStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Budget) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Budget) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Budget) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// BudgetAmount specifies the monetary limit and currency for a budget.
type BudgetAmount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         float64                `protobuf:"fixed64,1,opt,name=limit,proto3" json:"limit,omitempty"`     // Maximum spending amount (required, > 0)
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"` // ISO 4217 currency code (required, 3 characters, e.g., "USD")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetAmount) Reset() {
	*x = BudgetAmount{}
	mi := &file_pulumicost_v1_budget_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetAmount) ProtoMessage() {}

func (x *BudgetAmount) ProtoReflect() protoreflect.Message {
	mi := &file_pulumicost_v1_budget_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetAmount.ProtoReflect.Descriptor instead.
func (*BudgetAmount) Descriptor() ([]byte, []int) {
	return file_pulumicost_v1_budget_proto_rawDescGZIP(), []int{1}
}

func (x *BudgetAmount) GetLimit() float64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *BudgetAmount) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// BudgetFilter allows narrowing down budgets by provider, region, resource type, or tags.
// All fields are optional - empty filter matches all budgets.
type BudgetFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []string               `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`                                                                 // Cloud provider restrictions (optional)
	Regions       []string               `protobuf:"bytes,2,rep,name=regions,proto3" json:"regions,omitempty"`                                                                     // Geographic region restrictions (optional)
	ResourceTypes []string               `protobuf:"bytes,3,rep,name=resource_types,json=resourceTypes,proto3" json:"resource_types,omitempty"`                                    // Resource type restrictions (optional)
	Tags          map[string]string      `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Tag-based filtering (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetFilter) Reset() {
	*x = BudgetFilter{}
	mi := &file_pulumicost_v1_budget_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetFilter) ProtoMessage() {}

func (x *BudgetFilter) ProtoReflect() protoreflect.Message {
	mi := &file_pulumicost_v1_budget_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetFilter.ProtoReflect.Descriptor instead.
func (*BudgetFilter) Descriptor() ([]byte, []int) {
	return file_pulumicost_v1_budget_proto_rawDescGZIP(), []int{2}
}

func (x *BudgetFilter) GetProviders() []string {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *BudgetFilter) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *BudgetFilter) GetResourceTypes() []string {
	if x != nil {
		return x.ResourceTypes
	}
	return nil
}

func (x *BudgetFilter) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// BudgetThreshold defines alert points with percentages and trigger types.
type BudgetThreshold struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Percentage    float64                `protobuf:"fixed64,1,opt,name=percentage,proto3" json:"percentage,omitempty"`                     // Alert threshold percentage (required, 0-100)
	Type          ThresholdType          `protobuf:"varint,2,opt,name=type,proto3,enum=pulumicost.v1.ThresholdType" json:"type,omitempty"` // Actual vs forecasted spending (required)
	Triggered     bool                   `protobuf:"varint,3,opt,name=triggered,proto3" json:"triggered,omitempty"`                        // Whether threshold has been crossed (optional)
	TriggeredAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=triggered_at,json=triggeredAt,proto3" json:"triggered_at,omitempty"`  // When threshold was crossed (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BudgetThreshold) Reset() {
	*x = BudgetThreshold{}
	mi := &file_pulumicost_v1_budget_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetThreshold) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetThreshold) ProtoMessage() {}

func (x *BudgetThreshold) ProtoReflect() protoreflect.Message {
	mi := &file_pulumicost_v1_budget_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetThreshold.ProtoReflect.Descriptor instead.
func (*BudgetThreshold) Descriptor() ([]byte, []int) {
	return file_pulumicost_v1_budget_proto_rawDescGZIP(), []int{3}
}

func (x *BudgetThreshold) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *BudgetThreshold) GetType() ThresholdType {
	if x != nil {
		return x.Type
	}
	return ThresholdType_THRESHOLD_TYPE_UNSPECIFIED
}

func (x *BudgetThreshold) GetTriggered() bool {
	if x != nil {
		return x.Triggered
	}
	return false
}

func (x *BudgetThreshold) GetTriggeredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TriggeredAt
	}
	return nil
}

// BudgetStatus shows current spending state and utilization metrics.
// Only populated when GetBudgetsRequest.include_status is true.
type BudgetStatus struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CurrentSpend         float64                `protobuf:"fixed64,1,opt,name=current_spend,json=currentSpend,proto3" json:"current_spend,omitempty"`                         // Actual spending to date (required)
	ForecastedSpend      float64                `protobuf:"fixed64,2,opt,name=forecasted_spend,json=forecastedSpend,proto3" json:"forecasted_spend,omitempty"`                // Predicted end-of-period spending (optional)
	PercentageUsed       float64                `protobuf:"fixed64,3,opt,name=percentage_used,json=percentageUsed,proto3" json:"percentage_used,omitempty"`                   // Current utilization percentage (required, can exceed 100 for exceeded budgets)
	PercentageForecasted float64                `protobuf:"fixed64,4,opt,name=percentage_forecasted,json=percentageForecasted,proto3" json:"percentage_forecasted,omitempty"` // Forecasted utilization percentage (optional, can exceed 100)
	Currency             string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`                                                       // Currency for spend amounts (required, 3 characters)
	Health               BudgetHealthStatus     `protobuf:"varint,6,opt,name=health,proto3,enum=pulumicost.v1.BudgetHealthStatus" json:"health,omitempty"`                    // Overall budget health assessment (required)
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *BudgetStatus) Reset() {
	*x = BudgetStatus{}
	mi := &file_pulumicost_v1_budget_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetStatus) ProtoMessage() {}

func (x *BudgetStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pulumicost_v1_budget_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetStatus.ProtoReflect.Descriptor instead.
func (*BudgetStatus) Descriptor() ([]byte, []int) {
	return file_pulumicost_v1_budget_proto_rawDescGZIP(), []int{4}
}

func (x *BudgetStatus) GetCurrentSpend() float64 {
	if x != nil {
		return x.CurrentSpend
	}
	return 0
}

func (x *BudgetStatus) GetForecastedSpend() float64 {
	if x != nil {
		return x.ForecastedSpend
	}
	return 0
}

func (x *BudgetStatus) GetPercentageUsed() float64 {
	if x != nil {
		return x.PercentageUsed
	}
	return 0
}

func (x *BudgetStatus) GetPercentageForecasted() float64 {
	if x != nil {
		return x.PercentageForecasted
	}
	return 0
}

func (x *BudgetStatus) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *BudgetStatus) GetHealth() BudgetHealthStatus {
	if x != nil {
		return x.Health
	}
	return BudgetHealthStatus_BUDGET_HEALTH_STATUS_UNSPECIFIED
}

// GetBudgetsRequest retrieves budget information with optional filtering.
// Use include_status=false for faster responses when current spend data isn't needed.
type GetBudgetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *BudgetFilter          `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`                                     // Optional filtering criteria
	IncludeStatus bool                   `protobuf:"varint,2,opt,name=include_status,json=includeStatus,proto3" json:"include_status,omitempty"` // Whether to fetch current spending status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBudgetsRequest) Reset() {
	*x = GetBudgetsRequest{}
	mi := &file_pulumicost_v1_budget_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBudgetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBudgetsRequest) ProtoMessage() {}

func (x *GetBudgetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pulumicost_v1_budget_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBudgetsRequest.ProtoReflect.Descriptor instead.
func (*GetBudgetsRequest) Descriptor() ([]byte, []int) {
	return file_pulumicost_v1_budget_proto_rawDescGZIP(), []int{5}
}

func (x *GetBudgetsRequest) GetFilter() *BudgetFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *GetBudgetsRequest) GetIncludeStatus() bool {
	if x != nil {
		return x.IncludeStatus
	}
	return false
}

// GetBudgetsResponse contains budget information and aggregated statistics.
type GetBudgetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Budgets       []*Budget              `protobuf:"bytes,1,rep,name=budgets,proto3" json:"budgets,omitempty"` // List of budget information
	Summary       *BudgetSummary         `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"` // Aggregated statistics across all budgets
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBudgetsResponse) Reset() {
	*x = GetBudgetsResponse{}
	mi := &file_pulumicost_v1_budget_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBudgetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBudgetsResponse) ProtoMessage() {}

func (x *GetBudgetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pulumicost_v1_budget_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBudgetsResponse.ProtoReflect.Descriptor instead.
func (*GetBudgetsResponse) Descriptor() ([]byte, []int) {
	return file_pulumicost_v1_budget_proto_rawDescGZIP(), []int{6}
}

func (x *GetBudgetsResponse) GetBudgets() []*Budget {
	if x != nil {
		return x.Budgets
	}
	return nil
}

func (x *GetBudgetsResponse) GetSummary() *BudgetSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

// BudgetSummary provides aggregated statistics across multiple budgets.
// Counts should sum to total_budgets (budgets_ok + budgets_warning + budgets_critical + budgets_exceeded).
type BudgetSummary struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalBudgets    int32                  `protobuf:"varint,1,opt,name=total_budgets,json=totalBudgets,proto3" json:"total_budgets,omitempty"`          // Total number of budgets returned
	BudgetsOk       int32                  `protobuf:"varint,2,opt,name=budgets_ok,json=budgetsOk,proto3" json:"budgets_ok,omitempty"`                   // Number of healthy budgets (OK status)
	BudgetsWarning  int32                  `protobuf:"varint,3,opt,name=budgets_warning,json=budgetsWarning,proto3" json:"budgets_warning,omitempty"`    // Number of warning budgets (approaching limits)
	BudgetsExceeded int32                  `protobuf:"varint,4,opt,name=budgets_exceeded,json=budgetsExceeded,proto3" json:"budgets_exceeded,omitempty"` // Number of exceeded budgets (over budget)
	BudgetsCritical int32                  `protobuf:"varint,5,opt,name=budgets_critical,json=budgetsCritical,proto3" json:"budgets_critical,omitempty"` // Number of critical budgets (near or at limits)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BudgetSummary) Reset() {
	*x = BudgetSummary{}
	mi := &file_pulumicost_v1_budget_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetSummary) ProtoMessage() {}

func (x *BudgetSummary) ProtoReflect() protoreflect.Message {
	mi := &file_pulumicost_v1_budget_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetSummary.ProtoReflect.Descriptor instead.
func (*BudgetSummary) Descriptor() ([]byte, []int) {
	return file_pulumicost_v1_budget_proto_rawDescGZIP(), []int{7}
}

func (x *BudgetSummary) GetTotalBudgets() int32 {
	if x != nil {
		return x.TotalBudgets
	}
	return 0
}

func (x *BudgetSummary) GetBudgetsOk() int32 {
	if x != nil {
		return x.BudgetsOk
	}
	return 0
}

func (x *BudgetSummary) GetBudgetsWarning() int32 {
	if x != nil {
		return x.BudgetsWarning
	}
	return 0
}

func (x *BudgetSummary) GetBudgetsExceeded() int32 {
	if x != nil {
		return x.BudgetsExceeded
	}
	return 0
}

func (x *BudgetSummary) GetBudgetsCritical() int32 {
	if x != nil {
		return x.BudgetsCritical
	}
	return 0
}

var File_pulumicost_v1_budget_proto protoreflect.FileDescriptor

const file_pulumicost_v1_budget_proto_rawDesc = "" +
	"\n" +
	"\x1apulumicost/v1/budget.proto\x12\rpulumicost.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcc\x04\n" +
	"\x06Budget\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x123\n" +
	"\x06amount\x18\x04 \x01(\v2\x1b.pulumicost.v1.BudgetAmountR\x06amount\x123\n" +
	"\x06period\x18\x05 \x01(\x0e2\x1b.pulumicost.v1.BudgetPeriodR\x06period\x123\n" +
	"\x06filter\x18\x06 \x01(\v2\x1b.pulumicost.v1.BudgetFilterR\x06filter\x12>\n" +
	"\n" +
	"thresholds\x18\a \x03(\v2\x1e.pulumicost.v1.BudgetThresholdR\n" +
	"thresholds\x123\n" +
	"\x06status\x18\b \x01(\v2\x1b.pulumicost.v1.BudgetStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12?\n" +
	"\bmetadata\x18\v \x03(\v2#.pulumicost.v1.Budget.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\fBudgetAmount\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x01R\x05limit\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\xe1\x01\n" +
	"\fBudgetFilter\x12\x1c\n" +
	"\tproviders\x18\x01 \x03(\tR\tproviders\x12\x18\n" +
	"\aregions\x18\x02 \x03(\tR\aregions\x12%\n" +
	"\x0eresource_types\x18\x03 \x03(\tR\rresourceTypes\x129\n" +
	"\x04tags\x18\x04 \x03(\v2%.pulumicost.v1.BudgetFilter.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc0\x01\n" +
	"\x0fBudgetThreshold\x12\x1e\n" +
	"\n" +
	"percentage\x18\x01 \x01(\x01R\n" +
	"percentage\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.pulumicost.v1.ThresholdTypeR\x04type\x12\x1c\n" +
	"\ttriggered\x18\x03 \x01(\bR\ttriggered\x12=\n" +
	"\ftriggered_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vtriggeredAt\"\x93\x02\n" +
	"\fBudgetStatus\x12#\n" +
	"\rcurrent_spend\x18\x01 \x01(\x01R\fcurrentSpend\x12)\n" +
	"\x10forecasted_spend\x18\x02 \x01(\x01R\x0fforecastedSpend\x12'\n" +
	"\x0fpercentage_used\x18\x03 \x01(\x01R\x0epercentageUsed\x123\n" +
	"\x15percentage_forecasted\x18\x04 \x01(\x01R\x14percentageForecasted\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x129\n" +
	"\x06health\x18\x06 \x01(\x0e2!.pulumicost.v1.BudgetHealthStatusR\x06health\"o\n" +
	"\x11GetBudgetsRequest\x123\n" +
	"\x06filter\x18\x01 \x01(\v2\x1b.pulumicost.v1.BudgetFilterR\x06filter\x12%\n" +
	"\x0einclude_status\x18\x02 \x01(\bR\rincludeStatus\"}\n" +
	"\x12GetBudgetsResponse\x12/\n" +
	"\abudgets\x18\x01 \x03(\v2\x15.pulumicost.v1.BudgetR\abudgets\x126\n" +
	"\asummary\x18\x02 \x01(\v2\x1c.pulumicost.v1.BudgetSummaryR\asummary\"\xd2\x01\n" +
	"\rBudgetSummary\x12#\n" +
	"\rtotal_budgets\x18\x01 \x01(\x05R\ftotalBudgets\x12\x1d\n" +
	"\n" +
	"budgets_ok\x18\x02 \x01(\x05R\tbudgetsOk\x12'\n" +
	"\x0fbudgets_warning\x18\x03 \x01(\x05R\x0ebudgetsWarning\x12)\n" +
	"\x10budgets_exceeded\x18\x04 \x01(\x05R\x0fbudgetsExceeded\x12)\n" +
	"\x10budgets_critical\x18\x05 \x01(\x05R\x0fbudgetsCritical*\xb4\x01\n" +
	"\fBudgetPeriod\x12\x1d\n" +
	"\x19BUDGET_PERIOD_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13BUDGET_PERIOD_DAILY\x10\x01\x12\x18\n" +
	"\x14BUDGET_PERIOD_WEEKLY\x10\x02\x12\x19\n" +
	"\x15BUDGET_PERIOD_MONTHLY\x10\x03\x12\x1b\n" +
	"\x17BUDGET_PERIOD_QUARTERLY\x10\x04\x12\x1a\n" +
	"\x16BUDGET_PERIOD_ANNUALLY\x10\x05*i\n" +
	"\rThresholdType\x12\x1e\n" +
	"\x1aTHRESHOLD_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15THRESHOLD_TYPE_ACTUAL\x10\x01\x12\x1d\n" +
	"\x19THRESHOLD_TYPE_FORECASTED\x10\x02*\xbf\x01\n" +
	"\x12BudgetHealthStatus\x12$\n" +
	" BUDGET_HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17BUDGET_HEALTH_STATUS_OK\x10\x01\x12 \n" +
	"\x1cBUDGET_HEALTH_STATUS_WARNING\x10\x02\x12!\n" +
	"\x1dBUDGET_HEALTH_STATUS_CRITICAL\x10\x03\x12!\n" +
	"\x1dBUDGET_HEALTH_STATUS_EXCEEDED\x10\x04B4Z2github.com/rshade/pulumicost-spec/sdk/go/proto;pbcb\x06proto3"

var (
	file_pulumicost_v1_budget_proto_rawDescOnce sync.Once
	file_pulumicost_v1_budget_proto_rawDescData []byte
)

func file_pulumicost_v1_budget_proto_rawDescGZIP() []byte {
	file_pulumicost_v1_budget_proto_rawDescOnce.Do(func() {
		file_pulumicost_v1_budget_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pulumicost_v1_budget_proto_rawDesc), len(file_pulumicost_v1_budget_proto_rawDesc)))
	})
	return file_pulumicost_v1_budget_proto_rawDescData
}

var file_pulumicost_v1_budget_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pulumicost_v1_budget_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pulumicost_v1_budget_proto_goTypes = []any{
	(BudgetPeriod)(0),             // 0: pulumicost.v1.BudgetPeriod
	(ThresholdType)(0),            // 1: pulumicost.v1.ThresholdType
	(BudgetHealthStatus)(0),       // 2: pulumicost.v1.BudgetHealthStatus
	(*Budget)(nil),                // 3: pulumicost.v1.Budget
	(*BudgetAmount)(nil),          // 4: pulumicost.v1.BudgetAmount
	(*BudgetFilter)(nil),          // 5: pulumicost.v1.BudgetFilter
	(*BudgetThreshold)(nil),       // 6: pulumicost.v1.BudgetThreshold
	(*BudgetStatus)(nil),          // 7: pulumicost.v1.BudgetStatus
	(*GetBudgetsRequest)(nil),     // 8: pulumicost.v1.GetBudgetsRequest
	(*GetBudgetsResponse)(nil),    // 9: pulumicost.v1.GetBudgetsResponse
	(*BudgetSummary)(nil),         // 10: pulumicost.v1.BudgetSummary
	nil,                           // 11: pulumicost.v1.Budget.MetadataEntry
	nil,                           // 12: pulumicost.v1.BudgetFilter.TagsEntry
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_pulumicost_v1_budget_proto_depIdxs = []int32{
	4,  // 0: pulumicost.v1.Budget.amount:type_name -> pulumicost.v1.BudgetAmount
	0,  // 1: pulumicost.v1.Budget.period:type_name -> pulumicost.v1.BudgetPeriod
	5,  // 2: pulumicost.v1.Budget.filter:type_name -> pulumicost.v1.BudgetFilter
	6,  // 3: pulumicost.v1.Budget.thresholds:type_name -> pulumicost.v1.BudgetThreshold
	7,  // 4: pulumicost.v1.Budget.status:type_name -> pulumicost.v1.BudgetStatus
	13, // 5: pulumicost.v1.Budget.created_at:type_name -> google.protobuf.Timestamp
	13, // 6: pulumicost.v1.Budget.updated_at:type_name -> google.protobuf.Timestamp
	11, // 7: pulumicost.v1.Budget.metadata:type_name -> pulumicost.v1.Budget.MetadataEntry
	12, // 8: pulumicost.v1.BudgetFilter.tags:type_name -> pulumicost.v1.BudgetFilter.TagsEntry
	1,  // 9: pulumicost.v1.BudgetThreshold.type:type_name -> pulumicost.v1.ThresholdType
	13, // 10: pulumicost.v1.BudgetThreshold.triggered_at:type_name -> google.protobuf.Timestamp
	2,  // 11: pulumicost.v1.BudgetStatus.health:type_name -> pulumicost.v1.BudgetHealthStatus
	5,  // 12: pulumicost.v1.GetBudgetsRequest.filter:type_name -> pulumicost.v1.BudgetFilter
	3,  // 13: pulumicost.v1.GetBudgetsResponse.budgets:type_name -> pulumicost.v1.Budget
	10, // 14: pulumicost.v1.GetBudgetsResponse.summary:type_name -> pulumicost.v1.BudgetSummary
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_pulumicost_v1_budget_proto_init() }
func file_pulumicost_v1_budget_proto_init() {
	if File_pulumicost_v1_budget_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pulumicost_v1_budget_proto_rawDesc), len(file_pulumicost_v1_budget_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pulumicost_v1_budget_proto_goTypes,
		DependencyIndexes: file_pulumicost_v1_budget_proto_depIdxs,
		EnumInfos:         file_pulumicost_v1_budget_proto_enumTypes,
		MessageInfos:      file_pulumicost_v1_budget_proto_msgTypes,
	}.Build()
	File_pulumicost_v1_budget_proto = out.File
	file_pulumicost_v1_budget_proto_goTypes = nil
	file_pulumicost_v1_budget_proto_depIdxs = nil
}
