// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: pulumicost/v1/enums.proto

package pbc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FocusServiceCategory represents the standard service classifications
// defined in FinOps FOCUS 1.2.
type FocusServiceCategory int32

const (
	FocusServiceCategory_FOCUS_SERVICE_CATEGORY_UNSPECIFIED      FocusServiceCategory = 0
	FocusServiceCategory_FOCUS_SERVICE_CATEGORY_COMPUTE          FocusServiceCategory = 1
	FocusServiceCategory_FOCUS_SERVICE_CATEGORY_STORAGE          FocusServiceCategory = 2
	FocusServiceCategory_FOCUS_SERVICE_CATEGORY_NETWORK          FocusServiceCategory = 3
	FocusServiceCategory_FOCUS_SERVICE_CATEGORY_DATABASE         FocusServiceCategory = 4
	FocusServiceCategory_FOCUS_SERVICE_CATEGORY_ANALYTICS        FocusServiceCategory = 5
	FocusServiceCategory_FOCUS_SERVICE_CATEGORY_MACHINE_LEARNING FocusServiceCategory = 6
	FocusServiceCategory_FOCUS_SERVICE_CATEGORY_MANAGEMENT       FocusServiceCategory = 7
	FocusServiceCategory_FOCUS_SERVICE_CATEGORY_SECURITY         FocusServiceCategory = 8
	FocusServiceCategory_FOCUS_SERVICE_CATEGORY_DEVELOPER_TOOLS  FocusServiceCategory = 9
	FocusServiceCategory_FOCUS_SERVICE_CATEGORY_OTHER            FocusServiceCategory = 10
)

// Enum value maps for FocusServiceCategory.
var (
	FocusServiceCategory_name = map[int32]string{
		0:  "FOCUS_SERVICE_CATEGORY_UNSPECIFIED",
		1:  "FOCUS_SERVICE_CATEGORY_COMPUTE",
		2:  "FOCUS_SERVICE_CATEGORY_STORAGE",
		3:  "FOCUS_SERVICE_CATEGORY_NETWORK",
		4:  "FOCUS_SERVICE_CATEGORY_DATABASE",
		5:  "FOCUS_SERVICE_CATEGORY_ANALYTICS",
		6:  "FOCUS_SERVICE_CATEGORY_MACHINE_LEARNING",
		7:  "FOCUS_SERVICE_CATEGORY_MANAGEMENT",
		8:  "FOCUS_SERVICE_CATEGORY_SECURITY",
		9:  "FOCUS_SERVICE_CATEGORY_DEVELOPER_TOOLS",
		10: "FOCUS_SERVICE_CATEGORY_OTHER",
	}
	FocusServiceCategory_value = map[string]int32{
		"FOCUS_SERVICE_CATEGORY_UNSPECIFIED":      0,
		"FOCUS_SERVICE_CATEGORY_COMPUTE":          1,
		"FOCUS_SERVICE_CATEGORY_STORAGE":          2,
		"FOCUS_SERVICE_CATEGORY_NETWORK":          3,
		"FOCUS_SERVICE_CATEGORY_DATABASE":         4,
		"FOCUS_SERVICE_CATEGORY_ANALYTICS":        5,
		"FOCUS_SERVICE_CATEGORY_MACHINE_LEARNING": 6,
		"FOCUS_SERVICE_CATEGORY_MANAGEMENT":       7,
		"FOCUS_SERVICE_CATEGORY_SECURITY":         8,
		"FOCUS_SERVICE_CATEGORY_DEVELOPER_TOOLS":  9,
		"FOCUS_SERVICE_CATEGORY_OTHER":            10,
	}
)

func (x FocusServiceCategory) Enum() *FocusServiceCategory {
	p := new(FocusServiceCategory)
	*p = x
	return p
}

func (x FocusServiceCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FocusServiceCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_pulumicost_v1_enums_proto_enumTypes[0].Descriptor()
}

func (FocusServiceCategory) Type() protoreflect.EnumType {
	return &file_pulumicost_v1_enums_proto_enumTypes[0]
}

func (x FocusServiceCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FocusServiceCategory.Descriptor instead.
func (FocusServiceCategory) EnumDescriptor() ([]byte, []int) {
	return file_pulumicost_v1_enums_proto_rawDescGZIP(), []int{0}
}

// FocusChargeCategory represents the nature of the charge.
type FocusChargeCategory int32

const (
	FocusChargeCategory_FOCUS_CHARGE_CATEGORY_UNSPECIFIED FocusChargeCategory = 0
	FocusChargeCategory_FOCUS_CHARGE_CATEGORY_USAGE       FocusChargeCategory = 1
	FocusChargeCategory_FOCUS_CHARGE_CATEGORY_PURCHASE    FocusChargeCategory = 2
	FocusChargeCategory_FOCUS_CHARGE_CATEGORY_CREDIT      FocusChargeCategory = 3
	FocusChargeCategory_FOCUS_CHARGE_CATEGORY_TAX         FocusChargeCategory = 4
	FocusChargeCategory_FOCUS_CHARGE_CATEGORY_REFUND      FocusChargeCategory = 5
	FocusChargeCategory_FOCUS_CHARGE_CATEGORY_ADJUSTMENT  FocusChargeCategory = 6
)

// Enum value maps for FocusChargeCategory.
var (
	FocusChargeCategory_name = map[int32]string{
		0: "FOCUS_CHARGE_CATEGORY_UNSPECIFIED",
		1: "FOCUS_CHARGE_CATEGORY_USAGE",
		2: "FOCUS_CHARGE_CATEGORY_PURCHASE",
		3: "FOCUS_CHARGE_CATEGORY_CREDIT",
		4: "FOCUS_CHARGE_CATEGORY_TAX",
		5: "FOCUS_CHARGE_CATEGORY_REFUND",
		6: "FOCUS_CHARGE_CATEGORY_ADJUSTMENT",
	}
	FocusChargeCategory_value = map[string]int32{
		"FOCUS_CHARGE_CATEGORY_UNSPECIFIED": 0,
		"FOCUS_CHARGE_CATEGORY_USAGE":       1,
		"FOCUS_CHARGE_CATEGORY_PURCHASE":    2,
		"FOCUS_CHARGE_CATEGORY_CREDIT":      3,
		"FOCUS_CHARGE_CATEGORY_TAX":         4,
		"FOCUS_CHARGE_CATEGORY_REFUND":      5,
		"FOCUS_CHARGE_CATEGORY_ADJUSTMENT":  6,
	}
)

func (x FocusChargeCategory) Enum() *FocusChargeCategory {
	p := new(FocusChargeCategory)
	*p = x
	return p
}

func (x FocusChargeCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FocusChargeCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_pulumicost_v1_enums_proto_enumTypes[1].Descriptor()
}

func (FocusChargeCategory) Type() protoreflect.EnumType {
	return &file_pulumicost_v1_enums_proto_enumTypes[1]
}

func (x FocusChargeCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FocusChargeCategory.Descriptor instead.
func (FocusChargeCategory) EnumDescriptor() ([]byte, []int) {
	return file_pulumicost_v1_enums_proto_rawDescGZIP(), []int{1}
}

// FocusPricingCategory represents the pricing model applied.
type FocusPricingCategory int32

const (
	FocusPricingCategory_FOCUS_PRICING_CATEGORY_UNSPECIFIED FocusPricingCategory = 0
	FocusPricingCategory_FOCUS_PRICING_CATEGORY_STANDARD    FocusPricingCategory = 1
	FocusPricingCategory_FOCUS_PRICING_CATEGORY_COMMITTED   FocusPricingCategory = 2
	FocusPricingCategory_FOCUS_PRICING_CATEGORY_DYNAMIC     FocusPricingCategory = 3
	FocusPricingCategory_FOCUS_PRICING_CATEGORY_OTHER       FocusPricingCategory = 4
)

// Enum value maps for FocusPricingCategory.
var (
	FocusPricingCategory_name = map[int32]string{
		0: "FOCUS_PRICING_CATEGORY_UNSPECIFIED",
		1: "FOCUS_PRICING_CATEGORY_STANDARD",
		2: "FOCUS_PRICING_CATEGORY_COMMITTED",
		3: "FOCUS_PRICING_CATEGORY_DYNAMIC",
		4: "FOCUS_PRICING_CATEGORY_OTHER",
	}
	FocusPricingCategory_value = map[string]int32{
		"FOCUS_PRICING_CATEGORY_UNSPECIFIED": 0,
		"FOCUS_PRICING_CATEGORY_STANDARD":    1,
		"FOCUS_PRICING_CATEGORY_COMMITTED":   2,
		"FOCUS_PRICING_CATEGORY_DYNAMIC":     3,
		"FOCUS_PRICING_CATEGORY_OTHER":       4,
	}
)

func (x FocusPricingCategory) Enum() *FocusPricingCategory {
	p := new(FocusPricingCategory)
	*p = x
	return p
}

func (x FocusPricingCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FocusPricingCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_pulumicost_v1_enums_proto_enumTypes[2].Descriptor()
}

func (FocusPricingCategory) Type() protoreflect.EnumType {
	return &file_pulumicost_v1_enums_proto_enumTypes[2]
}

func (x FocusPricingCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FocusPricingCategory.Descriptor instead.
func (FocusPricingCategory) EnumDescriptor() ([]byte, []int) {
	return file_pulumicost_v1_enums_proto_rawDescGZIP(), []int{2}
}

var File_pulumicost_v1_enums_proto protoreflect.FileDescriptor

const file_pulumicost_v1_enums_proto_rawDesc = "" +
	"\n" +
	"\x19pulumicost/v1/enums.proto\x12\rpulumicost.v1*\xbc\x03\n" +
	"\x14FocusServiceCategory\x12&\n" +
	"\"FOCUS_SERVICE_CATEGORY_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eFOCUS_SERVICE_CATEGORY_COMPUTE\x10\x01\x12\"\n" +
	"\x1eFOCUS_SERVICE_CATEGORY_STORAGE\x10\x02\x12\"\n" +
	"\x1eFOCUS_SERVICE_CATEGORY_NETWORK\x10\x03\x12#\n" +
	"\x1fFOCUS_SERVICE_CATEGORY_DATABASE\x10\x04\x12$\n" +
	" FOCUS_SERVICE_CATEGORY_ANALYTICS\x10\x05\x12+\n" +
	"'FOCUS_SERVICE_CATEGORY_MACHINE_LEARNING\x10\x06\x12%\n" +
	"!FOCUS_SERVICE_CATEGORY_MANAGEMENT\x10\a\x12#\n" +
	"\x1fFOCUS_SERVICE_CATEGORY_SECURITY\x10\b\x12*\n" +
	"&FOCUS_SERVICE_CATEGORY_DEVELOPER_TOOLS\x10\t\x12 \n" +
	"\x1cFOCUS_SERVICE_CATEGORY_OTHER\x10\n" +
	"*\x8a\x02\n" +
	"\x13FocusChargeCategory\x12%\n" +
	"!FOCUS_CHARGE_CATEGORY_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bFOCUS_CHARGE_CATEGORY_USAGE\x10\x01\x12\"\n" +
	"\x1eFOCUS_CHARGE_CATEGORY_PURCHASE\x10\x02\x12 \n" +
	"\x1cFOCUS_CHARGE_CATEGORY_CREDIT\x10\x03\x12\x1d\n" +
	"\x19FOCUS_CHARGE_CATEGORY_TAX\x10\x04\x12 \n" +
	"\x1cFOCUS_CHARGE_CATEGORY_REFUND\x10\x05\x12$\n" +
	" FOCUS_CHARGE_CATEGORY_ADJUSTMENT\x10\x06*\xcf\x01\n" +
	"\x14FocusPricingCategory\x12&\n" +
	"\"FOCUS_PRICING_CATEGORY_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fFOCUS_PRICING_CATEGORY_STANDARD\x10\x01\x12$\n" +
	" FOCUS_PRICING_CATEGORY_COMMITTED\x10\x02\x12\"\n" +
	"\x1eFOCUS_PRICING_CATEGORY_DYNAMIC\x10\x03\x12 \n" +
	"\x1cFOCUS_PRICING_CATEGORY_OTHER\x10\x04B4Z2github.com/rshade/pulumicost-spec/sdk/go/proto;pbcb\x06proto3"

var (
	file_pulumicost_v1_enums_proto_rawDescOnce sync.Once
	file_pulumicost_v1_enums_proto_rawDescData []byte
)

func file_pulumicost_v1_enums_proto_rawDescGZIP() []byte {
	file_pulumicost_v1_enums_proto_rawDescOnce.Do(func() {
		file_pulumicost_v1_enums_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pulumicost_v1_enums_proto_rawDesc), len(file_pulumicost_v1_enums_proto_rawDesc)))
	})
	return file_pulumicost_v1_enums_proto_rawDescData
}

var file_pulumicost_v1_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pulumicost_v1_enums_proto_goTypes = []any{
	(FocusServiceCategory)(0), // 0: pulumicost.v1.FocusServiceCategory
	(FocusChargeCategory)(0),  // 1: pulumicost.v1.FocusChargeCategory
	(FocusPricingCategory)(0), // 2: pulumicost.v1.FocusPricingCategory
}
var file_pulumicost_v1_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pulumicost_v1_enums_proto_init() }
func file_pulumicost_v1_enums_proto_init() {
	if File_pulumicost_v1_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pulumicost_v1_enums_proto_rawDesc), len(file_pulumicost_v1_enums_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pulumicost_v1_enums_proto_goTypes,
		DependencyIndexes: file_pulumicost_v1_enums_proto_depIdxs,
		EnumInfos:         file_pulumicost_v1_enums_proto_enumTypes,
	}.Build()
	File_pulumicost_v1_enums_proto = out.File
	file_pulumicost_v1_enums_proto_goTypes = nil
	file_pulumicost_v1_enums_proto_depIdxs = nil
}
