// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: pulumicost/v1/enums.proto

package pbc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FocusServiceCategory represents the standard service classifications
// defined in FinOps FOCUS 1.2.
type FocusServiceCategory int32

const (
	FocusServiceCategory_FOCUS_SERVICE_CATEGORY_UNSPECIFIED      FocusServiceCategory = 0
	FocusServiceCategory_FOCUS_SERVICE_CATEGORY_COMPUTE          FocusServiceCategory = 1
	FocusServiceCategory_FOCUS_SERVICE_CATEGORY_STORAGE          FocusServiceCategory = 2
	FocusServiceCategory_FOCUS_SERVICE_CATEGORY_NETWORK          FocusServiceCategory = 3
	FocusServiceCategory_FOCUS_SERVICE_CATEGORY_DATABASE         FocusServiceCategory = 4
	FocusServiceCategory_FOCUS_SERVICE_CATEGORY_ANALYTICS        FocusServiceCategory = 5
	FocusServiceCategory_FOCUS_SERVICE_CATEGORY_MACHINE_LEARNING FocusServiceCategory = 6
	FocusServiceCategory_FOCUS_SERVICE_CATEGORY_MANAGEMENT       FocusServiceCategory = 7
	FocusServiceCategory_FOCUS_SERVICE_CATEGORY_SECURITY         FocusServiceCategory = 8
	FocusServiceCategory_FOCUS_SERVICE_CATEGORY_DEVELOPER_TOOLS  FocusServiceCategory = 9
	FocusServiceCategory_FOCUS_SERVICE_CATEGORY_OTHER            FocusServiceCategory = 10
)

// Enum value maps for FocusServiceCategory.
var (
	FocusServiceCategory_name = map[int32]string{
		0:  "FOCUS_SERVICE_CATEGORY_UNSPECIFIED",
		1:  "FOCUS_SERVICE_CATEGORY_COMPUTE",
		2:  "FOCUS_SERVICE_CATEGORY_STORAGE",
		3:  "FOCUS_SERVICE_CATEGORY_NETWORK",
		4:  "FOCUS_SERVICE_CATEGORY_DATABASE",
		5:  "FOCUS_SERVICE_CATEGORY_ANALYTICS",
		6:  "FOCUS_SERVICE_CATEGORY_MACHINE_LEARNING",
		7:  "FOCUS_SERVICE_CATEGORY_MANAGEMENT",
		8:  "FOCUS_SERVICE_CATEGORY_SECURITY",
		9:  "FOCUS_SERVICE_CATEGORY_DEVELOPER_TOOLS",
		10: "FOCUS_SERVICE_CATEGORY_OTHER",
	}
	FocusServiceCategory_value = map[string]int32{
		"FOCUS_SERVICE_CATEGORY_UNSPECIFIED":      0,
		"FOCUS_SERVICE_CATEGORY_COMPUTE":          1,
		"FOCUS_SERVICE_CATEGORY_STORAGE":          2,
		"FOCUS_SERVICE_CATEGORY_NETWORK":          3,
		"FOCUS_SERVICE_CATEGORY_DATABASE":         4,
		"FOCUS_SERVICE_CATEGORY_ANALYTICS":        5,
		"FOCUS_SERVICE_CATEGORY_MACHINE_LEARNING": 6,
		"FOCUS_SERVICE_CATEGORY_MANAGEMENT":       7,
		"FOCUS_SERVICE_CATEGORY_SECURITY":         8,
		"FOCUS_SERVICE_CATEGORY_DEVELOPER_TOOLS":  9,
		"FOCUS_SERVICE_CATEGORY_OTHER":            10,
	}
)

func (x FocusServiceCategory) Enum() *FocusServiceCategory {
	p := new(FocusServiceCategory)
	*p = x
	return p
}

func (x FocusServiceCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FocusServiceCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_pulumicost_v1_enums_proto_enumTypes[0].Descriptor()
}

func (FocusServiceCategory) Type() protoreflect.EnumType {
	return &file_pulumicost_v1_enums_proto_enumTypes[0]
}

func (x FocusServiceCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FocusServiceCategory.Descriptor instead.
func (FocusServiceCategory) EnumDescriptor() ([]byte, []int) {
	return file_pulumicost_v1_enums_proto_rawDescGZIP(), []int{0}
}

// FocusChargeCategory represents the nature of the charge.
type FocusChargeCategory int32

const (
	FocusChargeCategory_FOCUS_CHARGE_CATEGORY_UNSPECIFIED FocusChargeCategory = 0
	FocusChargeCategory_FOCUS_CHARGE_CATEGORY_USAGE       FocusChargeCategory = 1
	FocusChargeCategory_FOCUS_CHARGE_CATEGORY_PURCHASE    FocusChargeCategory = 2
	FocusChargeCategory_FOCUS_CHARGE_CATEGORY_CREDIT      FocusChargeCategory = 3
	FocusChargeCategory_FOCUS_CHARGE_CATEGORY_TAX         FocusChargeCategory = 4
	FocusChargeCategory_FOCUS_CHARGE_CATEGORY_REFUND      FocusChargeCategory = 5
	FocusChargeCategory_FOCUS_CHARGE_CATEGORY_ADJUSTMENT  FocusChargeCategory = 6
)

// Enum value maps for FocusChargeCategory.
var (
	FocusChargeCategory_name = map[int32]string{
		0: "FOCUS_CHARGE_CATEGORY_UNSPECIFIED",
		1: "FOCUS_CHARGE_CATEGORY_USAGE",
		2: "FOCUS_CHARGE_CATEGORY_PURCHASE",
		3: "FOCUS_CHARGE_CATEGORY_CREDIT",
		4: "FOCUS_CHARGE_CATEGORY_TAX",
		5: "FOCUS_CHARGE_CATEGORY_REFUND",
		6: "FOCUS_CHARGE_CATEGORY_ADJUSTMENT",
	}
	FocusChargeCategory_value = map[string]int32{
		"FOCUS_CHARGE_CATEGORY_UNSPECIFIED": 0,
		"FOCUS_CHARGE_CATEGORY_USAGE":       1,
		"FOCUS_CHARGE_CATEGORY_PURCHASE":    2,
		"FOCUS_CHARGE_CATEGORY_CREDIT":      3,
		"FOCUS_CHARGE_CATEGORY_TAX":         4,
		"FOCUS_CHARGE_CATEGORY_REFUND":      5,
		"FOCUS_CHARGE_CATEGORY_ADJUSTMENT":  6,
	}
)

func (x FocusChargeCategory) Enum() *FocusChargeCategory {
	p := new(FocusChargeCategory)
	*p = x
	return p
}

func (x FocusChargeCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FocusChargeCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_pulumicost_v1_enums_proto_enumTypes[1].Descriptor()
}

func (FocusChargeCategory) Type() protoreflect.EnumType {
	return &file_pulumicost_v1_enums_proto_enumTypes[1]
}

func (x FocusChargeCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FocusChargeCategory.Descriptor instead.
func (FocusChargeCategory) EnumDescriptor() ([]byte, []int) {
	return file_pulumicost_v1_enums_proto_rawDescGZIP(), []int{1}
}

// FocusPricingCategory represents the pricing model applied.
// FOCUS 1.2 Section 2.4: Pricing Category
type FocusPricingCategory int32

const (
	FocusPricingCategory_FOCUS_PRICING_CATEGORY_UNSPECIFIED FocusPricingCategory = 0
	FocusPricingCategory_FOCUS_PRICING_CATEGORY_STANDARD    FocusPricingCategory = 1
	FocusPricingCategory_FOCUS_PRICING_CATEGORY_COMMITTED   FocusPricingCategory = 2
	FocusPricingCategory_FOCUS_PRICING_CATEGORY_DYNAMIC     FocusPricingCategory = 3
	FocusPricingCategory_FOCUS_PRICING_CATEGORY_OTHER       FocusPricingCategory = 4
)

// Enum value maps for FocusPricingCategory.
var (
	FocusPricingCategory_name = map[int32]string{
		0: "FOCUS_PRICING_CATEGORY_UNSPECIFIED",
		1: "FOCUS_PRICING_CATEGORY_STANDARD",
		2: "FOCUS_PRICING_CATEGORY_COMMITTED",
		3: "FOCUS_PRICING_CATEGORY_DYNAMIC",
		4: "FOCUS_PRICING_CATEGORY_OTHER",
	}
	FocusPricingCategory_value = map[string]int32{
		"FOCUS_PRICING_CATEGORY_UNSPECIFIED": 0,
		"FOCUS_PRICING_CATEGORY_STANDARD":    1,
		"FOCUS_PRICING_CATEGORY_COMMITTED":   2,
		"FOCUS_PRICING_CATEGORY_DYNAMIC":     3,
		"FOCUS_PRICING_CATEGORY_OTHER":       4,
	}
)

func (x FocusPricingCategory) Enum() *FocusPricingCategory {
	p := new(FocusPricingCategory)
	*p = x
	return p
}

func (x FocusPricingCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FocusPricingCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_pulumicost_v1_enums_proto_enumTypes[2].Descriptor()
}

func (FocusPricingCategory) Type() protoreflect.EnumType {
	return &file_pulumicost_v1_enums_proto_enumTypes[2]
}

func (x FocusPricingCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FocusPricingCategory.Descriptor instead.
func (FocusPricingCategory) EnumDescriptor() ([]byte, []int) {
	return file_pulumicost_v1_enums_proto_rawDescGZIP(), []int{2}
}

// FocusChargeClass represents the classification of charges.
// FOCUS 1.2 Section 2.4: Charge Class (New in 1.0+)
type FocusChargeClass int32

const (
	FocusChargeClass_FOCUS_CHARGE_CLASS_UNSPECIFIED FocusChargeClass = 0
	FocusChargeClass_FOCUS_CHARGE_CLASS_REGULAR     FocusChargeClass = 1
	FocusChargeClass_FOCUS_CHARGE_CLASS_CORRECTION  FocusChargeClass = 2
)

// Enum value maps for FocusChargeClass.
var (
	FocusChargeClass_name = map[int32]string{
		0: "FOCUS_CHARGE_CLASS_UNSPECIFIED",
		1: "FOCUS_CHARGE_CLASS_REGULAR",
		2: "FOCUS_CHARGE_CLASS_CORRECTION",
	}
	FocusChargeClass_value = map[string]int32{
		"FOCUS_CHARGE_CLASS_UNSPECIFIED": 0,
		"FOCUS_CHARGE_CLASS_REGULAR":     1,
		"FOCUS_CHARGE_CLASS_CORRECTION":  2,
	}
)

func (x FocusChargeClass) Enum() *FocusChargeClass {
	p := new(FocusChargeClass)
	*p = x
	return p
}

func (x FocusChargeClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FocusChargeClass) Descriptor() protoreflect.EnumDescriptor {
	return file_pulumicost_v1_enums_proto_enumTypes[3].Descriptor()
}

func (FocusChargeClass) Type() protoreflect.EnumType {
	return &file_pulumicost_v1_enums_proto_enumTypes[3]
}

func (x FocusChargeClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FocusChargeClass.Descriptor instead.
func (FocusChargeClass) EnumDescriptor() ([]byte, []int) {
	return file_pulumicost_v1_enums_proto_rawDescGZIP(), []int{3}
}

// FocusChargeFrequency represents how often a charge is applied.
// FOCUS 1.2 Section 2.4: Charge Frequency
type FocusChargeFrequency int32

const (
	FocusChargeFrequency_FOCUS_CHARGE_FREQUENCY_UNSPECIFIED FocusChargeFrequency = 0
	FocusChargeFrequency_FOCUS_CHARGE_FREQUENCY_ONE_TIME    FocusChargeFrequency = 1
	FocusChargeFrequency_FOCUS_CHARGE_FREQUENCY_RECURRING   FocusChargeFrequency = 2
	FocusChargeFrequency_FOCUS_CHARGE_FREQUENCY_USAGE_BASED FocusChargeFrequency = 3
)

// Enum value maps for FocusChargeFrequency.
var (
	FocusChargeFrequency_name = map[int32]string{
		0: "FOCUS_CHARGE_FREQUENCY_UNSPECIFIED",
		1: "FOCUS_CHARGE_FREQUENCY_ONE_TIME",
		2: "FOCUS_CHARGE_FREQUENCY_RECURRING",
		3: "FOCUS_CHARGE_FREQUENCY_USAGE_BASED",
	}
	FocusChargeFrequency_value = map[string]int32{
		"FOCUS_CHARGE_FREQUENCY_UNSPECIFIED": 0,
		"FOCUS_CHARGE_FREQUENCY_ONE_TIME":    1,
		"FOCUS_CHARGE_FREQUENCY_RECURRING":   2,
		"FOCUS_CHARGE_FREQUENCY_USAGE_BASED": 3,
	}
)

func (x FocusChargeFrequency) Enum() *FocusChargeFrequency {
	p := new(FocusChargeFrequency)
	*p = x
	return p
}

func (x FocusChargeFrequency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FocusChargeFrequency) Descriptor() protoreflect.EnumDescriptor {
	return file_pulumicost_v1_enums_proto_enumTypes[4].Descriptor()
}

func (FocusChargeFrequency) Type() protoreflect.EnumType {
	return &file_pulumicost_v1_enums_proto_enumTypes[4]
}

func (x FocusChargeFrequency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FocusChargeFrequency.Descriptor instead.
func (FocusChargeFrequency) EnumDescriptor() ([]byte, []int) {
	return file_pulumicost_v1_enums_proto_rawDescGZIP(), []int{4}
}

// FocusCommitmentDiscountCategory represents the type of commitment discount.
// FOCUS 1.2 Section 2.6: Commitment Discounts
type FocusCommitmentDiscountCategory int32

const (
	FocusCommitmentDiscountCategory_FOCUS_COMMITMENT_DISCOUNT_CATEGORY_UNSPECIFIED FocusCommitmentDiscountCategory = 0
	FocusCommitmentDiscountCategory_FOCUS_COMMITMENT_DISCOUNT_CATEGORY_SPEND       FocusCommitmentDiscountCategory = 1
	FocusCommitmentDiscountCategory_FOCUS_COMMITMENT_DISCOUNT_CATEGORY_USAGE       FocusCommitmentDiscountCategory = 2
)

// Enum value maps for FocusCommitmentDiscountCategory.
var (
	FocusCommitmentDiscountCategory_name = map[int32]string{
		0: "FOCUS_COMMITMENT_DISCOUNT_CATEGORY_UNSPECIFIED",
		1: "FOCUS_COMMITMENT_DISCOUNT_CATEGORY_SPEND",
		2: "FOCUS_COMMITMENT_DISCOUNT_CATEGORY_USAGE",
	}
	FocusCommitmentDiscountCategory_value = map[string]int32{
		"FOCUS_COMMITMENT_DISCOUNT_CATEGORY_UNSPECIFIED": 0,
		"FOCUS_COMMITMENT_DISCOUNT_CATEGORY_SPEND":       1,
		"FOCUS_COMMITMENT_DISCOUNT_CATEGORY_USAGE":       2,
	}
)

func (x FocusCommitmentDiscountCategory) Enum() *FocusCommitmentDiscountCategory {
	p := new(FocusCommitmentDiscountCategory)
	*p = x
	return p
}

func (x FocusCommitmentDiscountCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FocusCommitmentDiscountCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_pulumicost_v1_enums_proto_enumTypes[5].Descriptor()
}

func (FocusCommitmentDiscountCategory) Type() protoreflect.EnumType {
	return &file_pulumicost_v1_enums_proto_enumTypes[5]
}

func (x FocusCommitmentDiscountCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FocusCommitmentDiscountCategory.Descriptor instead.
func (FocusCommitmentDiscountCategory) EnumDescriptor() ([]byte, []int) {
	return file_pulumicost_v1_enums_proto_rawDescGZIP(), []int{5}
}

// FocusCommitmentDiscountStatus represents the utilization status of a
// commitment discount. FOCUS 1.2 Section 3.17: Commitment Discount Status
type FocusCommitmentDiscountStatus int32

const (
	FocusCommitmentDiscountStatus_FOCUS_COMMITMENT_DISCOUNT_STATUS_UNSPECIFIED FocusCommitmentDiscountStatus = 0
	// Used: Charges utilizing a specific commitment discount amount.
	FocusCommitmentDiscountStatus_FOCUS_COMMITMENT_DISCOUNT_STATUS_USED FocusCommitmentDiscountStatus = 1
	// Unused: Charges representing the unused portion of a commitment discount.
	FocusCommitmentDiscountStatus_FOCUS_COMMITMENT_DISCOUNT_STATUS_UNUSED FocusCommitmentDiscountStatus = 2
)

// Enum value maps for FocusCommitmentDiscountStatus.
var (
	FocusCommitmentDiscountStatus_name = map[int32]string{
		0: "FOCUS_COMMITMENT_DISCOUNT_STATUS_UNSPECIFIED",
		1: "FOCUS_COMMITMENT_DISCOUNT_STATUS_USED",
		2: "FOCUS_COMMITMENT_DISCOUNT_STATUS_UNUSED",
	}
	FocusCommitmentDiscountStatus_value = map[string]int32{
		"FOCUS_COMMITMENT_DISCOUNT_STATUS_UNSPECIFIED": 0,
		"FOCUS_COMMITMENT_DISCOUNT_STATUS_USED":        1,
		"FOCUS_COMMITMENT_DISCOUNT_STATUS_UNUSED":      2,
	}
)

func (x FocusCommitmentDiscountStatus) Enum() *FocusCommitmentDiscountStatus {
	p := new(FocusCommitmentDiscountStatus)
	*p = x
	return p
}

func (x FocusCommitmentDiscountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FocusCommitmentDiscountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pulumicost_v1_enums_proto_enumTypes[6].Descriptor()
}

func (FocusCommitmentDiscountStatus) Type() protoreflect.EnumType {
	return &file_pulumicost_v1_enums_proto_enumTypes[6]
}

func (x FocusCommitmentDiscountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FocusCommitmentDiscountStatus.Descriptor instead.
func (FocusCommitmentDiscountStatus) EnumDescriptor() ([]byte, []int) {
	return file_pulumicost_v1_enums_proto_rawDescGZIP(), []int{6}
}

// FocusCapacityReservationStatus represents the utilization status of a
// capacity reservation. FOCUS 1.2 Section 3.7: Capacity Reservation Status
type FocusCapacityReservationStatus int32

const (
	FocusCapacityReservationStatus_FOCUS_CAPACITY_RESERVATION_STATUS_UNSPECIFIED FocusCapacityReservationStatus = 0
	// Used: Charges utilizing a specific capacity reservation amount.
	FocusCapacityReservationStatus_FOCUS_CAPACITY_RESERVATION_STATUS_USED FocusCapacityReservationStatus = 1
	// Unused: Charges representing the unused portion of a capacity reservation.
	FocusCapacityReservationStatus_FOCUS_CAPACITY_RESERVATION_STATUS_UNUSED FocusCapacityReservationStatus = 2
)

// Enum value maps for FocusCapacityReservationStatus.
var (
	FocusCapacityReservationStatus_name = map[int32]string{
		0: "FOCUS_CAPACITY_RESERVATION_STATUS_UNSPECIFIED",
		1: "FOCUS_CAPACITY_RESERVATION_STATUS_USED",
		2: "FOCUS_CAPACITY_RESERVATION_STATUS_UNUSED",
	}
	FocusCapacityReservationStatus_value = map[string]int32{
		"FOCUS_CAPACITY_RESERVATION_STATUS_UNSPECIFIED": 0,
		"FOCUS_CAPACITY_RESERVATION_STATUS_USED":        1,
		"FOCUS_CAPACITY_RESERVATION_STATUS_UNUSED":      2,
	}
)

func (x FocusCapacityReservationStatus) Enum() *FocusCapacityReservationStatus {
	p := new(FocusCapacityReservationStatus)
	*p = x
	return p
}

func (x FocusCapacityReservationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FocusCapacityReservationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pulumicost_v1_enums_proto_enumTypes[7].Descriptor()
}

func (FocusCapacityReservationStatus) Type() protoreflect.EnumType {
	return &file_pulumicost_v1_enums_proto_enumTypes[7]
}

func (x FocusCapacityReservationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FocusCapacityReservationStatus.Descriptor instead.
func (FocusCapacityReservationStatus) EnumDescriptor() ([]byte, []int) {
	return file_pulumicost_v1_enums_proto_rawDescGZIP(), []int{7}
}

var File_pulumicost_v1_enums_proto protoreflect.FileDescriptor

const file_pulumicost_v1_enums_proto_rawDesc = "" +
	"\n" +
	"\x19pulumicost/v1/enums.proto\x12\rpulumicost.v1*\xbc\x03\n" +
	"\x14FocusServiceCategory\x12&\n" +
	"\"FOCUS_SERVICE_CATEGORY_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eFOCUS_SERVICE_CATEGORY_COMPUTE\x10\x01\x12\"\n" +
	"\x1eFOCUS_SERVICE_CATEGORY_STORAGE\x10\x02\x12\"\n" +
	"\x1eFOCUS_SERVICE_CATEGORY_NETWORK\x10\x03\x12#\n" +
	"\x1fFOCUS_SERVICE_CATEGORY_DATABASE\x10\x04\x12$\n" +
	" FOCUS_SERVICE_CATEGORY_ANALYTICS\x10\x05\x12+\n" +
	"'FOCUS_SERVICE_CATEGORY_MACHINE_LEARNING\x10\x06\x12%\n" +
	"!FOCUS_SERVICE_CATEGORY_MANAGEMENT\x10\a\x12#\n" +
	"\x1fFOCUS_SERVICE_CATEGORY_SECURITY\x10\b\x12*\n" +
	"&FOCUS_SERVICE_CATEGORY_DEVELOPER_TOOLS\x10\t\x12 \n" +
	"\x1cFOCUS_SERVICE_CATEGORY_OTHER\x10\n" +
	"*\x8a\x02\n" +
	"\x13FocusChargeCategory\x12%\n" +
	"!FOCUS_CHARGE_CATEGORY_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bFOCUS_CHARGE_CATEGORY_USAGE\x10\x01\x12\"\n" +
	"\x1eFOCUS_CHARGE_CATEGORY_PURCHASE\x10\x02\x12 \n" +
	"\x1cFOCUS_CHARGE_CATEGORY_CREDIT\x10\x03\x12\x1d\n" +
	"\x19FOCUS_CHARGE_CATEGORY_TAX\x10\x04\x12 \n" +
	"\x1cFOCUS_CHARGE_CATEGORY_REFUND\x10\x05\x12$\n" +
	" FOCUS_CHARGE_CATEGORY_ADJUSTMENT\x10\x06*\xcf\x01\n" +
	"\x14FocusPricingCategory\x12&\n" +
	"\"FOCUS_PRICING_CATEGORY_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fFOCUS_PRICING_CATEGORY_STANDARD\x10\x01\x12$\n" +
	" FOCUS_PRICING_CATEGORY_COMMITTED\x10\x02\x12\"\n" +
	"\x1eFOCUS_PRICING_CATEGORY_DYNAMIC\x10\x03\x12 \n" +
	"\x1cFOCUS_PRICING_CATEGORY_OTHER\x10\x04*y\n" +
	"\x10FocusChargeClass\x12\"\n" +
	"\x1eFOCUS_CHARGE_CLASS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aFOCUS_CHARGE_CLASS_REGULAR\x10\x01\x12!\n" +
	"\x1dFOCUS_CHARGE_CLASS_CORRECTION\x10\x02*\xb1\x01\n" +
	"\x14FocusChargeFrequency\x12&\n" +
	"\"FOCUS_CHARGE_FREQUENCY_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fFOCUS_CHARGE_FREQUENCY_ONE_TIME\x10\x01\x12$\n" +
	" FOCUS_CHARGE_FREQUENCY_RECURRING\x10\x02\x12&\n" +
	"\"FOCUS_CHARGE_FREQUENCY_USAGE_BASED\x10\x03*\xb1\x01\n" +
	"\x1fFocusCommitmentDiscountCategory\x122\n" +
	".FOCUS_COMMITMENT_DISCOUNT_CATEGORY_UNSPECIFIED\x10\x00\x12,\n" +
	"(FOCUS_COMMITMENT_DISCOUNT_CATEGORY_SPEND\x10\x01\x12,\n" +
	"(FOCUS_COMMITMENT_DISCOUNT_CATEGORY_USAGE\x10\x02*\xa9\x01\n" +
	"\x1dFocusCommitmentDiscountStatus\x120\n" +
	",FOCUS_COMMITMENT_DISCOUNT_STATUS_UNSPECIFIED\x10\x00\x12)\n" +
	"%FOCUS_COMMITMENT_DISCOUNT_STATUS_USED\x10\x01\x12+\n" +
	"'FOCUS_COMMITMENT_DISCOUNT_STATUS_UNUSED\x10\x02*\xad\x01\n" +
	"\x1eFocusCapacityReservationStatus\x121\n" +
	"-FOCUS_CAPACITY_RESERVATION_STATUS_UNSPECIFIED\x10\x00\x12*\n" +
	"&FOCUS_CAPACITY_RESERVATION_STATUS_USED\x10\x01\x12,\n" +
	"(FOCUS_CAPACITY_RESERVATION_STATUS_UNUSED\x10\x02B4Z2github.com/rshade/pulumicost-spec/sdk/go/proto;pbcb\x06proto3"

var (
	file_pulumicost_v1_enums_proto_rawDescOnce sync.Once
	file_pulumicost_v1_enums_proto_rawDescData []byte
)

func file_pulumicost_v1_enums_proto_rawDescGZIP() []byte {
	file_pulumicost_v1_enums_proto_rawDescOnce.Do(func() {
		file_pulumicost_v1_enums_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pulumicost_v1_enums_proto_rawDesc), len(file_pulumicost_v1_enums_proto_rawDesc)))
	})
	return file_pulumicost_v1_enums_proto_rawDescData
}

var file_pulumicost_v1_enums_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_pulumicost_v1_enums_proto_goTypes = []any{
	(FocusServiceCategory)(0),            // 0: pulumicost.v1.FocusServiceCategory
	(FocusChargeCategory)(0),             // 1: pulumicost.v1.FocusChargeCategory
	(FocusPricingCategory)(0),            // 2: pulumicost.v1.FocusPricingCategory
	(FocusChargeClass)(0),                // 3: pulumicost.v1.FocusChargeClass
	(FocusChargeFrequency)(0),            // 4: pulumicost.v1.FocusChargeFrequency
	(FocusCommitmentDiscountCategory)(0), // 5: pulumicost.v1.FocusCommitmentDiscountCategory
	(FocusCommitmentDiscountStatus)(0),   // 6: pulumicost.v1.FocusCommitmentDiscountStatus
	(FocusCapacityReservationStatus)(0),  // 7: pulumicost.v1.FocusCapacityReservationStatus
}
var file_pulumicost_v1_enums_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pulumicost_v1_enums_proto_init() }
func file_pulumicost_v1_enums_proto_init() {
	if File_pulumicost_v1_enums_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pulumicost_v1_enums_proto_rawDesc), len(file_pulumicost_v1_enums_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pulumicost_v1_enums_proto_goTypes,
		DependencyIndexes: file_pulumicost_v1_enums_proto_depIdxs,
		EnumInfos:         file_pulumicost_v1_enums_proto_enumTypes,
	}.Build()
	File_pulumicost_v1_enums_proto = out.File
	file_pulumicost_v1_enums_proto_goTypes = nil
	file_pulumicost_v1_enums_proto_depIdxs = nil
}
