// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: pulumicost/v1/focus.proto

package pbc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FocusCostRecord represents a single cost line item normalized to the
// FinOps FOCUS 1.2 specification.
type FocusCostRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// --- Identity & Hierarchy ---
	ProviderName       string `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	BillingAccountId   string `protobuf:"bytes,2,opt,name=billing_account_id,json=billingAccountId,proto3" json:"billing_account_id,omitempty"`
	BillingAccountName string `protobuf:"bytes,3,opt,name=billing_account_name,json=billingAccountName,proto3" json:"billing_account_name,omitempty"`
	// --- Time ---
	ChargePeriodStart *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=charge_period_start,json=chargePeriodStart,proto3" json:"charge_period_start,omitempty"`
	ChargePeriodEnd   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=charge_period_end,json=chargePeriodEnd,proto3" json:"charge_period_end,omitempty"`
	// --- Service & Product ---
	ServiceCategory FocusServiceCategory `protobuf:"varint,6,opt,name=service_category,json=serviceCategory,proto3,enum=pulumicost.v1.FocusServiceCategory" json:"service_category,omitempty"`
	ServiceName     string               `protobuf:"bytes,7,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ResourceId      string               `protobuf:"bytes,12,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceName    string               `protobuf:"bytes,13,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	SkuId           string               `protobuf:"bytes,14,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	RegionId        string               `protobuf:"bytes,10,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	RegionName      string               `protobuf:"bytes,11,opt,name=region_name,json=regionName,proto3" json:"region_name,omitempty"`
	// --- Charge Details ---
	ChargeCategory  FocusChargeCategory  `protobuf:"varint,8,opt,name=charge_category,json=chargeCategory,proto3,enum=pulumicost.v1.FocusChargeCategory" json:"charge_category,omitempty"`
	PricingCategory FocusPricingCategory `protobuf:"varint,9,opt,name=pricing_category,json=pricingCategory,proto3,enum=pulumicost.v1.FocusPricingCategory" json:"pricing_category,omitempty"`
	// --- Financials ---
	BilledCost    float64 `protobuf:"fixed64,15,opt,name=billed_cost,json=billedCost,proto3" json:"billed_cost,omitempty"`
	ListCost      float64 `protobuf:"fixed64,16,opt,name=list_cost,json=listCost,proto3" json:"list_cost,omitempty"`
	EffectiveCost float64 `protobuf:"fixed64,17,opt,name=effective_cost,json=effectiveCost,proto3" json:"effective_cost,omitempty"`
	Currency      string  `protobuf:"bytes,18,opt,name=currency,proto3" json:"currency,omitempty"`
	InvoiceId     string  `protobuf:"bytes,19,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	// --- Usage ---
	UsageQuantity float64 `protobuf:"fixed64,20,opt,name=usage_quantity,json=usageQuantity,proto3" json:"usage_quantity,omitempty"`
	UsageUnit     string  `protobuf:"bytes,21,opt,name=usage_unit,json=usageUnit,proto3" json:"usage_unit,omitempty"`
	// --- Metadata & Extension ---
	Tags map[string]string `protobuf:"bytes,22,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The "Backpack": Supports future FOCUS columns or provider-specific
	// extensions without requiring a schema update.
	ExtendedColumns map[string]string `protobuf:"bytes,23,rep,name=extended_columns,json=extendedColumns,proto3" json:"extended_columns,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FocusCostRecord) Reset() {
	*x = FocusCostRecord{}
	mi := &file_pulumicost_v1_focus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FocusCostRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FocusCostRecord) ProtoMessage() {}

func (x *FocusCostRecord) ProtoReflect() protoreflect.Message {
	mi := &file_pulumicost_v1_focus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FocusCostRecord.ProtoReflect.Descriptor instead.
func (*FocusCostRecord) Descriptor() ([]byte, []int) {
	return file_pulumicost_v1_focus_proto_rawDescGZIP(), []int{0}
}

func (x *FocusCostRecord) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *FocusCostRecord) GetBillingAccountId() string {
	if x != nil {
		return x.BillingAccountId
	}
	return ""
}

func (x *FocusCostRecord) GetBillingAccountName() string {
	if x != nil {
		return x.BillingAccountName
	}
	return ""
}

func (x *FocusCostRecord) GetChargePeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.ChargePeriodStart
	}
	return nil
}

func (x *FocusCostRecord) GetChargePeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.ChargePeriodEnd
	}
	return nil
}

func (x *FocusCostRecord) GetServiceCategory() FocusServiceCategory {
	if x != nil {
		return x.ServiceCategory
	}
	return FocusServiceCategory_FOCUS_SERVICE_CATEGORY_UNSPECIFIED
}

func (x *FocusCostRecord) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *FocusCostRecord) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *FocusCostRecord) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *FocusCostRecord) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

func (x *FocusCostRecord) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

func (x *FocusCostRecord) GetRegionName() string {
	if x != nil {
		return x.RegionName
	}
	return ""
}

func (x *FocusCostRecord) GetChargeCategory() FocusChargeCategory {
	if x != nil {
		return x.ChargeCategory
	}
	return FocusChargeCategory_FOCUS_CHARGE_CATEGORY_UNSPECIFIED
}

func (x *FocusCostRecord) GetPricingCategory() FocusPricingCategory {
	if x != nil {
		return x.PricingCategory
	}
	return FocusPricingCategory_FOCUS_PRICING_CATEGORY_UNSPECIFIED
}

func (x *FocusCostRecord) GetBilledCost() float64 {
	if x != nil {
		return x.BilledCost
	}
	return 0
}

func (x *FocusCostRecord) GetListCost() float64 {
	if x != nil {
		return x.ListCost
	}
	return 0
}

func (x *FocusCostRecord) GetEffectiveCost() float64 {
	if x != nil {
		return x.EffectiveCost
	}
	return 0
}

func (x *FocusCostRecord) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FocusCostRecord) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *FocusCostRecord) GetUsageQuantity() float64 {
	if x != nil {
		return x.UsageQuantity
	}
	return 0
}

func (x *FocusCostRecord) GetUsageUnit() string {
	if x != nil {
		return x.UsageUnit
	}
	return ""
}

func (x *FocusCostRecord) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *FocusCostRecord) GetExtendedColumns() map[string]string {
	if x != nil {
		return x.ExtendedColumns
	}
	return nil
}

var File_pulumicost_v1_focus_proto protoreflect.FileDescriptor

const file_pulumicost_v1_focus_proto_rawDesc = "" +
	"\n" +
	"\x19pulumicost/v1/focus.proto\x12\rpulumicost.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19pulumicost/v1/enums.proto\"\xd6\t\n" +
	"\x0fFocusCostRecord\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12,\n" +
	"\x12billing_account_id\x18\x02 \x01(\tR\x10billingAccountId\x120\n" +
	"\x14billing_account_name\x18\x03 \x01(\tR\x12billingAccountName\x12J\n" +
	"\x13charge_period_start\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x11chargePeriodStart\x12F\n" +
	"\x11charge_period_end\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0fchargePeriodEnd\x12N\n" +
	"\x10service_category\x18\x06 \x01(\x0e2#.pulumicost.v1.FocusServiceCategoryR\x0fserviceCategory\x12!\n" +
	"\fservice_name\x18\a \x01(\tR\vserviceName\x12\x1f\n" +
	"\vresource_id\x18\f \x01(\tR\n" +
	"resourceId\x12#\n" +
	"\rresource_name\x18\r \x01(\tR\fresourceName\x12\x15\n" +
	"\x06sku_id\x18\x0e \x01(\tR\x05skuId\x12\x1b\n" +
	"\tregion_id\x18\n" +
	" \x01(\tR\bregionId\x12\x1f\n" +
	"\vregion_name\x18\v \x01(\tR\n" +
	"regionName\x12K\n" +
	"\x0fcharge_category\x18\b \x01(\x0e2\".pulumicost.v1.FocusChargeCategoryR\x0echargeCategory\x12N\n" +
	"\x10pricing_category\x18\t \x01(\x0e2#.pulumicost.v1.FocusPricingCategoryR\x0fpricingCategory\x12\x1f\n" +
	"\vbilled_cost\x18\x0f \x01(\x01R\n" +
	"billedCost\x12\x1b\n" +
	"\tlist_cost\x18\x10 \x01(\x01R\blistCost\x12%\n" +
	"\x0eeffective_cost\x18\x11 \x01(\x01R\reffectiveCost\x12\x1a\n" +
	"\bcurrency\x18\x12 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x13 \x01(\tR\tinvoiceId\x12%\n" +
	"\x0eusage_quantity\x18\x14 \x01(\x01R\rusageQuantity\x12\x1d\n" +
	"\n" +
	"usage_unit\x18\x15 \x01(\tR\tusageUnit\x12<\n" +
	"\x04tags\x18\x16 \x03(\v2(.pulumicost.v1.FocusCostRecord.TagsEntryR\x04tags\x12^\n" +
	"\x10extended_columns\x18\x17 \x03(\v23.pulumicost.v1.FocusCostRecord.ExtendedColumnsEntryR\x0fextendedColumns\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14ExtendedColumnsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B4Z2github.com/rshade/pulumicost-spec/sdk/go/proto;pbcb\x06proto3"

var (
	file_pulumicost_v1_focus_proto_rawDescOnce sync.Once
	file_pulumicost_v1_focus_proto_rawDescData []byte
)

func file_pulumicost_v1_focus_proto_rawDescGZIP() []byte {
	file_pulumicost_v1_focus_proto_rawDescOnce.Do(func() {
		file_pulumicost_v1_focus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pulumicost_v1_focus_proto_rawDesc), len(file_pulumicost_v1_focus_proto_rawDesc)))
	})
	return file_pulumicost_v1_focus_proto_rawDescData
}

var file_pulumicost_v1_focus_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pulumicost_v1_focus_proto_goTypes = []any{
	(*FocusCostRecord)(nil),       // 0: pulumicost.v1.FocusCostRecord
	nil,                           // 1: pulumicost.v1.FocusCostRecord.TagsEntry
	nil,                           // 2: pulumicost.v1.FocusCostRecord.ExtendedColumnsEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(FocusServiceCategory)(0),     // 4: pulumicost.v1.FocusServiceCategory
	(FocusChargeCategory)(0),      // 5: pulumicost.v1.FocusChargeCategory
	(FocusPricingCategory)(0),     // 6: pulumicost.v1.FocusPricingCategory
}
var file_pulumicost_v1_focus_proto_depIdxs = []int32{
	3, // 0: pulumicost.v1.FocusCostRecord.charge_period_start:type_name -> google.protobuf.Timestamp
	3, // 1: pulumicost.v1.FocusCostRecord.charge_period_end:type_name -> google.protobuf.Timestamp
	4, // 2: pulumicost.v1.FocusCostRecord.service_category:type_name -> pulumicost.v1.FocusServiceCategory
	5, // 3: pulumicost.v1.FocusCostRecord.charge_category:type_name -> pulumicost.v1.FocusChargeCategory
	6, // 4: pulumicost.v1.FocusCostRecord.pricing_category:type_name -> pulumicost.v1.FocusPricingCategory
	1, // 5: pulumicost.v1.FocusCostRecord.tags:type_name -> pulumicost.v1.FocusCostRecord.TagsEntry
	2, // 6: pulumicost.v1.FocusCostRecord.extended_columns:type_name -> pulumicost.v1.FocusCostRecord.ExtendedColumnsEntry
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_pulumicost_v1_focus_proto_init() }
func file_pulumicost_v1_focus_proto_init() {
	if File_pulumicost_v1_focus_proto != nil {
		return
	}
	file_pulumicost_v1_enums_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pulumicost_v1_focus_proto_rawDesc), len(file_pulumicost_v1_focus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pulumicost_v1_focus_proto_goTypes,
		DependencyIndexes: file_pulumicost_v1_focus_proto_depIdxs,
		MessageInfos:      file_pulumicost_v1_focus_proto_msgTypes,
	}.Build()
	File_pulumicost_v1_focus_proto = out.File
	file_pulumicost_v1_focus_proto_goTypes = nil
	file_pulumicost_v1_focus_proto_depIdxs = nil
}
