// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pulumicost/v1/focus.proto

package pbc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FocusContractCommitmentCategory represents the type of commitment in the
// FOCUS 1.3 Contract Commitment Dataset.
// Reference: FOCUS 1.3 Contract Commitment Category
type FocusContractCommitmentCategory int32

const (
	// Default/unspecified value.
	FocusContractCommitmentCategory_FOCUS_CONTRACT_COMMITMENT_CATEGORY_UNSPECIFIED FocusContractCommitmentCategory = 0
	// Monetary spend commitment (e.g., $10,000/month minimum).
	FocusContractCommitmentCategory_FOCUS_CONTRACT_COMMITMENT_CATEGORY_SPEND FocusContractCommitmentCategory = 1
	// Usage quantity commitment (e.g., 1000 compute hours).
	FocusContractCommitmentCategory_FOCUS_CONTRACT_COMMITMENT_CATEGORY_USAGE FocusContractCommitmentCategory = 2
)

// Enum value maps for FocusContractCommitmentCategory.
var (
	FocusContractCommitmentCategory_name = map[int32]string{
		0: "FOCUS_CONTRACT_COMMITMENT_CATEGORY_UNSPECIFIED",
		1: "FOCUS_CONTRACT_COMMITMENT_CATEGORY_SPEND",
		2: "FOCUS_CONTRACT_COMMITMENT_CATEGORY_USAGE",
	}
	FocusContractCommitmentCategory_value = map[string]int32{
		"FOCUS_CONTRACT_COMMITMENT_CATEGORY_UNSPECIFIED": 0,
		"FOCUS_CONTRACT_COMMITMENT_CATEGORY_SPEND":       1,
		"FOCUS_CONTRACT_COMMITMENT_CATEGORY_USAGE":       2,
	}
)

func (x FocusContractCommitmentCategory) Enum() *FocusContractCommitmentCategory {
	p := new(FocusContractCommitmentCategory)
	*p = x
	return p
}

func (x FocusContractCommitmentCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FocusContractCommitmentCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_pulumicost_v1_focus_proto_enumTypes[0].Descriptor()
}

func (FocusContractCommitmentCategory) Type() protoreflect.EnumType {
	return &file_pulumicost_v1_focus_proto_enumTypes[0]
}

func (x FocusContractCommitmentCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FocusContractCommitmentCategory.Descriptor instead.
func (FocusContractCommitmentCategory) EnumDescriptor() ([]byte, []int) {
	return file_pulumicost_v1_focus_proto_rawDescGZIP(), []int{0}
}

// FocusCostRecord represents a single cost line item normalized to the
// FinOps FOCUS specification (1.2 and 1.3). All field names follow FOCUS naming conventions.
// Includes FOCUS 1.3 additions: allocation fields, contract commitment linking,
// and service/host provider disambiguation.
// Reference: https://focus.finops.org
type FocusCostRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ProviderName: The name of the cloud provider (e.g., "AWS", "Azure", "GCP").
	// DEPRECATED in FOCUS 1.3: Use service_provider_name instead.
	// Will be removed in FOCUS 1.4.
	//
	// Deprecated: Marked as deprecated in pulumicost/v1/focus.proto.
	ProviderName string `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	// BillingAccountId: The identifier for the billing account.
	BillingAccountId string `protobuf:"bytes,2,opt,name=billing_account_id,json=billingAccountId,proto3" json:"billing_account_id,omitempty"`
	// BillingAccountName: The display name for the billing account.
	BillingAccountName string `protobuf:"bytes,3,opt,name=billing_account_name,json=billingAccountName,proto3" json:"billing_account_name,omitempty"`
	// SubAccountId: The identifier for the sub-account (e.g., AWS Account ID,
	// Azure Subscription ID, GCP Project ID).
	SubAccountId string `protobuf:"bytes,24,opt,name=sub_account_id,json=subAccountId,proto3" json:"sub_account_id,omitempty"`
	// SubAccountName: The display name for the sub-account.
	SubAccountName string `protobuf:"bytes,25,opt,name=sub_account_name,json=subAccountName,proto3" json:"sub_account_name,omitempty"`
	// BillingAccountType: Provider-assigned name to identify the type of billing
	// account. FOCUS 1.2 Section 3.3: Billing Account Type (CONDITIONAL).
	BillingAccountType string `protobuf:"bytes,42,opt,name=billing_account_type,json=billingAccountType,proto3" json:"billing_account_type,omitempty"`
	// SubAccountType: Provider-assigned identifier for sub-account classification.
	// FOCUS 1.2 Section 3.45: Sub Account Type (CONDITIONAL).
	SubAccountType string `protobuf:"bytes,43,opt,name=sub_account_type,json=subAccountType,proto3" json:"sub_account_type,omitempty"`
	// BillingPeriodStart: The start date/time of the billing period.
	BillingPeriodStart *timestamppb.Timestamp `protobuf:"bytes,26,opt,name=billing_period_start,json=billingPeriodStart,proto3" json:"billing_period_start,omitempty"`
	// BillingPeriodEnd: The end date/time of the billing period.
	BillingPeriodEnd *timestamppb.Timestamp `protobuf:"bytes,27,opt,name=billing_period_end,json=billingPeriodEnd,proto3" json:"billing_period_end,omitempty"`
	// BillingCurrency: The currency used for billing (ISO 4217 code).
	BillingCurrency string `protobuf:"bytes,18,opt,name=billing_currency,json=billingCurrency,proto3" json:"billing_currency,omitempty"`
	// ChargePeriodStart: The start date/time when the charge was incurred.
	ChargePeriodStart *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=charge_period_start,json=chargePeriodStart,proto3" json:"charge_period_start,omitempty"`
	// ChargePeriodEnd: The end date/time when the charge was incurred.
	ChargePeriodEnd *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=charge_period_end,json=chargePeriodEnd,proto3" json:"charge_period_end,omitempty"`
	// ChargeCategory: The nature of the charge (Usage, Purchase, Credit, etc.).
	ChargeCategory FocusChargeCategory `protobuf:"varint,8,opt,name=charge_category,json=chargeCategory,proto3,enum=pulumicost.v1.FocusChargeCategory" json:"charge_category,omitempty"`
	// ChargeClass: Classification of the charge (Regular, Correction).
	// New in FOCUS 1.0+.
	ChargeClass FocusChargeClass `protobuf:"varint,28,opt,name=charge_class,json=chargeClass,proto3,enum=pulumicost.v1.FocusChargeClass" json:"charge_class,omitempty"`
	// ChargeDescription: A human-readable description of the charge.
	ChargeDescription string `protobuf:"bytes,29,opt,name=charge_description,json=chargeDescription,proto3" json:"charge_description,omitempty"`
	// ChargeFrequency: How often the charge is applied (OneTime, Recurring, UsageBased).
	ChargeFrequency FocusChargeFrequency `protobuf:"varint,30,opt,name=charge_frequency,json=chargeFrequency,proto3,enum=pulumicost.v1.FocusChargeFrequency" json:"charge_frequency,omitempty"`
	// PricingCategory: The pricing model applied (Standard, Committed, Dynamic).
	PricingCategory FocusPricingCategory `protobuf:"varint,9,opt,name=pricing_category,json=pricingCategory,proto3,enum=pulumicost.v1.FocusPricingCategory" json:"pricing_category,omitempty"`
	// PricingQuantity: The quantity used for pricing calculations.
	PricingQuantity float64 `protobuf:"fixed64,31,opt,name=pricing_quantity,json=pricingQuantity,proto3" json:"pricing_quantity,omitempty"`
	// PricingUnit: The unit of measure for pricing (e.g., "Hours", "GB").
	PricingUnit string `protobuf:"bytes,32,opt,name=pricing_unit,json=pricingUnit,proto3" json:"pricing_unit,omitempty"`
	// ListUnitPrice: The published unit price before any discounts.
	ListUnitPrice float64 `protobuf:"fixed64,33,opt,name=list_unit_price,json=listUnitPrice,proto3" json:"list_unit_price,omitempty"`
	// PricingCurrency: Currency for pricing-related columns when different from
	// billing currency. FOCUS 1.2 Section 3.34: Pricing Currency (CONDITIONAL).
	// Format: ISO 4217 currency code.
	PricingCurrency string `protobuf:"bytes,51,opt,name=pricing_currency,json=pricingCurrency,proto3" json:"pricing_currency,omitempty"`
	// PricingCurrencyContractedUnitPrice: Contracted unit price denominated in
	// pricing currency. FOCUS 1.2 Section 3.35 (CONDITIONAL).
	PricingCurrencyContractedUnitPrice float64 `protobuf:"fixed64,52,opt,name=pricing_currency_contracted_unit_price,json=pricingCurrencyContractedUnitPrice,proto3" json:"pricing_currency_contracted_unit_price,omitempty"`
	// PricingCurrencyEffectiveCost: Effective cost denominated in pricing
	// currency. FOCUS 1.2 Section 3.36 (CONDITIONAL).
	PricingCurrencyEffectiveCost float64 `protobuf:"fixed64,53,opt,name=pricing_currency_effective_cost,json=pricingCurrencyEffectiveCost,proto3" json:"pricing_currency_effective_cost,omitempty"`
	// PricingCurrencyListUnitPrice: List unit price denominated in pricing
	// currency. FOCUS 1.2 Section 3.37 (CONDITIONAL).
	PricingCurrencyListUnitPrice float64 `protobuf:"fixed64,54,opt,name=pricing_currency_list_unit_price,json=pricingCurrencyListUnitPrice,proto3" json:"pricing_currency_list_unit_price,omitempty"`
	// ServiceCategory: The category of the service (Compute, Storage, Network, etc.).
	ServiceCategory FocusServiceCategory `protobuf:"varint,6,opt,name=service_category,json=serviceCategory,proto3,enum=pulumicost.v1.FocusServiceCategory" json:"service_category,omitempty"`
	// ServiceName: The name of the service (e.g., "Amazon EC2", "Azure VMs").
	ServiceName string `protobuf:"bytes,7,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// ServiceSubcategory: Granular service classification supporting functional
	// categorization. FOCUS 1.2 Section 3.43: Service Subcategory (CONDITIONAL).
	ServiceSubcategory string `protobuf:"bytes,56,opt,name=service_subcategory,json=serviceSubcategory,proto3" json:"service_subcategory,omitempty"`
	// Publisher: Entity that published the service or product.
	// FOCUS 1.2 Section 3.39: Publisher (CONDITIONAL).
	// DEPRECATED in FOCUS 1.3: Use host_provider_name instead.
	// Will be removed in FOCUS 1.4.
	//
	// Deprecated: Marked as deprecated in pulumicost/v1/focus.proto.
	Publisher string `protobuf:"bytes,55,opt,name=publisher,proto3" json:"publisher,omitempty"`
	// ResourceId: The unique identifier for the resource.
	ResourceId string `protobuf:"bytes,12,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	// ResourceName: The display name of the resource.
	ResourceName string `protobuf:"bytes,13,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	// ResourceType: The type of resource (e.g., "m5.large", "Standard_D2s_v3").
	ResourceType string `protobuf:"bytes,34,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	// SkuId: The identifier for the SKU.
	SkuId string `protobuf:"bytes,14,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	// SkuPriceId: The identifier for the specific SKU price.
	SkuPriceId string `protobuf:"bytes,35,opt,name=sku_price_id,json=skuPriceId,proto3" json:"sku_price_id,omitempty"`
	// SkuMeter: Provider-assigned meter identifier for the SKU.
	// FOCUS 1.2 Section 3.46: SKU Meter (CONDITIONAL).
	SkuMeter string `protobuf:"bytes,57,opt,name=sku_meter,json=skuMeter,proto3" json:"sku_meter,omitempty"`
	// SkuPriceDetails: Additional provider-specific pricing details.
	// FOCUS 1.2 Section 3.48: SKU Price Details (CONDITIONAL).
	SkuPriceDetails string `protobuf:"bytes,58,opt,name=sku_price_details,json=skuPriceDetails,proto3" json:"sku_price_details,omitempty"`
	// RegionId: The identifier for the region (e.g., "us-east-1", "eastus").
	RegionId string `protobuf:"bytes,10,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	// RegionName: The display name of the region.
	RegionName string `protobuf:"bytes,11,opt,name=region_name,json=regionName,proto3" json:"region_name,omitempty"`
	// AvailabilityZone: The availability zone within the region (conditional).
	AvailabilityZone string `protobuf:"bytes,36,opt,name=availability_zone,json=availabilityZone,proto3" json:"availability_zone,omitempty"`
	// BilledCost: The amount billed for the charge.
	BilledCost float64 `protobuf:"fixed64,15,opt,name=billed_cost,json=billedCost,proto3" json:"billed_cost,omitempty"`
	// ListCost: The cost at list price before any discounts.
	ListCost float64 `protobuf:"fixed64,16,opt,name=list_cost,json=listCost,proto3" json:"list_cost,omitempty"`
	// EffectiveCost: The actual cost after all discounts and adjustments.
	EffectiveCost float64 `protobuf:"fixed64,17,opt,name=effective_cost,json=effectiveCost,proto3" json:"effective_cost,omitempty"`
	// ContractedCost: Cost calculated by multiplying contracted unit price and
	// pricing quantity. FOCUS 1.2 Section 3.20: Contracted Cost (MANDATORY).
	// Constraint: Must equal ContractedUnitPrice × PricingQuantity when both
	// are present and ChargeClass is not "Correction".
	ContractedCost float64 `protobuf:"fixed64,41,opt,name=contracted_cost,json=contractedCost,proto3" json:"contracted_cost,omitempty"`
	// ContractedUnitPrice: Agreed-upon unit price per pricing unit for the
	// associated SKU. FOCUS 1.2 Section 3.21: Contracted Unit Price (CONDITIONAL).
	ContractedUnitPrice float64 `protobuf:"fixed64,50,opt,name=contracted_unit_price,json=contractedUnitPrice,proto3" json:"contracted_unit_price,omitempty"`
	// ConsumedQuantity: The amount of usage consumed.
	ConsumedQuantity float64 `protobuf:"fixed64,20,opt,name=consumed_quantity,json=consumedQuantity,proto3" json:"consumed_quantity,omitempty"`
	// ConsumedUnit: The unit of measure for consumption (e.g., "Hours", "GB").
	ConsumedUnit string `protobuf:"bytes,21,opt,name=consumed_unit,json=consumedUnit,proto3" json:"consumed_unit,omitempty"`
	// CommitmentDiscountCategory: The type of commitment discount (Spend, Usage).
	CommitmentDiscountCategory FocusCommitmentDiscountCategory `protobuf:"varint,37,opt,name=commitment_discount_category,json=commitmentDiscountCategory,proto3,enum=pulumicost.v1.FocusCommitmentDiscountCategory" json:"commitment_discount_category,omitempty"`
	// CommitmentDiscountId: The identifier for the commitment discount.
	CommitmentDiscountId string `protobuf:"bytes,38,opt,name=commitment_discount_id,json=commitmentDiscountId,proto3" json:"commitment_discount_id,omitempty"`
	// CommitmentDiscountName: The display name of the commitment discount.
	CommitmentDiscountName string `protobuf:"bytes,39,opt,name=commitment_discount_name,json=commitmentDiscountName,proto3" json:"commitment_discount_name,omitempty"`
	// CommitmentDiscountQuantity: Amount of commitment discount purchased or
	// accounted for. FOCUS 1.2 Section 3.14 (CONDITIONAL).
	CommitmentDiscountQuantity float64 `protobuf:"fixed64,46,opt,name=commitment_discount_quantity,json=commitmentDiscountQuantity,proto3" json:"commitment_discount_quantity,omitempty"`
	// CommitmentDiscountStatus: Utilization status of commitment discount.
	// FOCUS 1.2 Section 3.17 (CONDITIONAL). Required when CommitmentDiscountId
	// is not null and ChargeCategory is "Usage".
	CommitmentDiscountStatus FocusCommitmentDiscountStatus `protobuf:"varint,47,opt,name=commitment_discount_status,json=commitmentDiscountStatus,proto3,enum=pulumicost.v1.FocusCommitmentDiscountStatus" json:"commitment_discount_status,omitempty"`
	// CommitmentDiscountType: Provider-assigned identifier for the type of
	// commitment discount applied. FOCUS 1.2 Section 3.18 (CONDITIONAL).
	CommitmentDiscountType string `protobuf:"bytes,48,opt,name=commitment_discount_type,json=commitmentDiscountType,proto3" json:"commitment_discount_type,omitempty"`
	// CommitmentDiscountUnit: Provider-specified measurement unit for commitment
	// discount quantity. FOCUS 1.2 Section 3.19 (CONDITIONAL).
	CommitmentDiscountUnit string `protobuf:"bytes,49,opt,name=commitment_discount_unit,json=commitmentDiscountUnit,proto3" json:"commitment_discount_unit,omitempty"`
	// CapacityReservationId: Identifier assigned to a capacity reservation by
	// the provider. FOCUS 1.2 Section 3.6 (CONDITIONAL).
	CapacityReservationId string `protobuf:"bytes,44,opt,name=capacity_reservation_id,json=capacityReservationId,proto3" json:"capacity_reservation_id,omitempty"`
	// CapacityReservationStatus: Utilization status of capacity reservation.
	// FOCUS 1.2 Section 3.7 (CONDITIONAL). Required when CapacityReservationId
	// is not null and ChargeCategory is "Usage".
	CapacityReservationStatus FocusCapacityReservationStatus `protobuf:"varint,45,opt,name=capacity_reservation_status,json=capacityReservationStatus,proto3,enum=pulumicost.v1.FocusCapacityReservationStatus" json:"capacity_reservation_status,omitempty"`
	// InvoiceId: The identifier for the invoice. Critical for reconciliation.
	InvoiceId string `protobuf:"bytes,19,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	// InvoiceIssuer: The entity that issued the invoice.
	InvoiceIssuer string `protobuf:"bytes,40,opt,name=invoice_issuer,json=invoiceIssuer,proto3" json:"invoice_issuer,omitempty"`
	// Tags: User-defined key-value pairs for resource tagging.
	Tags map[string]string `protobuf:"bytes,22,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// ExtendedColumns: The "Backpack" - supports future FOCUS columns or
	// provider-specific extensions without requiring a schema update.
	ExtendedColumns map[string]string `protobuf:"bytes,23,rep,name=extended_columns,json=extendedColumns,proto3" json:"extended_columns,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// ServiceProviderName: The entity that makes the service available for purchase.
	// In reseller/marketplace scenarios, this is the ISV or reseller.
	// Replaces deprecated provider_name field.
	// FOCUS 1.3 Section: Service Provider Name (CONDITIONAL)
	ServiceProviderName string `protobuf:"bytes,59,opt,name=service_provider_name,json=serviceProviderName,proto3" json:"service_provider_name,omitempty"`
	// HostProviderName: The entity that hosts the underlying resource or service.
	// This is where the workload actually runs (e.g., AWS, Azure, GCP).
	// Replaces deprecated publisher field.
	// FOCUS 1.3 Section: Host Provider Name (CONDITIONAL)
	HostProviderName string `protobuf:"bytes,60,opt,name=host_provider_name,json=hostProviderName,proto3" json:"host_provider_name,omitempty"`
	// AllocatedMethodId: Identifier for the cost allocation methodology used.
	// Links to a documented allocation method.
	// Validation: If populated, allocated_resource_id MUST also be populated.
	// FOCUS 1.3 Section: Allocated Method ID (CONDITIONAL)
	AllocatedMethodId string `protobuf:"bytes,61,opt,name=allocated_method_id,json=allocatedMethodId,proto3" json:"allocated_method_id,omitempty"`
	// AllocatedMethodDetails: Human-readable description of the allocation method.
	// Provides transparency into how costs were split.
	// FOCUS 1.3 Section: Allocated Method Details (RECOMMENDED)
	AllocatedMethodDetails string `protobuf:"bytes,62,opt,name=allocated_method_details,json=allocatedMethodDetails,proto3" json:"allocated_method_details,omitempty"`
	// AllocatedResourceId: Identifier of the resource receiving the allocated cost.
	// This is the target of the cost allocation.
	// FOCUS 1.3 Section: Allocated Resource ID (CONDITIONAL)
	AllocatedResourceId string `protobuf:"bytes,63,opt,name=allocated_resource_id,json=allocatedResourceId,proto3" json:"allocated_resource_id,omitempty"`
	// AllocatedResourceName: Display name of the resource receiving allocated cost.
	// FOCUS 1.3 Section: Allocated Resource Name (CONDITIONAL)
	AllocatedResourceName string `protobuf:"bytes,64,opt,name=allocated_resource_name,json=allocatedResourceName,proto3" json:"allocated_resource_name,omitempty"`
	// AllocatedTags: Tags associated with the allocated resource.
	// Follows same map<string, string> pattern as existing tags field.
	// FOCUS 1.3 Section: Allocated Tags (CONDITIONAL)
	AllocatedTags map[string]string `protobuf:"bytes,65,rep,name=allocated_tags,json=allocatedTags,proto3" json:"allocated_tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// ContractApplied: Reference to a ContractCommitmentId in the Contract
	// Commitment dataset. Treated as opaque reference (no cross-dataset validation).
	// FOCUS 1.3 Section: Contract Applied (CONDITIONAL)
	ContractApplied string `protobuf:"bytes,66,opt,name=contract_applied,json=contractApplied,proto3" json:"contract_applied,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FocusCostRecord) Reset() {
	*x = FocusCostRecord{}
	mi := &file_pulumicost_v1_focus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FocusCostRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FocusCostRecord) ProtoMessage() {}

func (x *FocusCostRecord) ProtoReflect() protoreflect.Message {
	mi := &file_pulumicost_v1_focus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FocusCostRecord.ProtoReflect.Descriptor instead.
func (*FocusCostRecord) Descriptor() ([]byte, []int) {
	return file_pulumicost_v1_focus_proto_rawDescGZIP(), []int{0}
}

// Deprecated: Marked as deprecated in pulumicost/v1/focus.proto.
func (x *FocusCostRecord) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *FocusCostRecord) GetBillingAccountId() string {
	if x != nil {
		return x.BillingAccountId
	}
	return ""
}

func (x *FocusCostRecord) GetBillingAccountName() string {
	if x != nil {
		return x.BillingAccountName
	}
	return ""
}

func (x *FocusCostRecord) GetSubAccountId() string {
	if x != nil {
		return x.SubAccountId
	}
	return ""
}

func (x *FocusCostRecord) GetSubAccountName() string {
	if x != nil {
		return x.SubAccountName
	}
	return ""
}

func (x *FocusCostRecord) GetBillingAccountType() string {
	if x != nil {
		return x.BillingAccountType
	}
	return ""
}

func (x *FocusCostRecord) GetSubAccountType() string {
	if x != nil {
		return x.SubAccountType
	}
	return ""
}

func (x *FocusCostRecord) GetBillingPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.BillingPeriodStart
	}
	return nil
}

func (x *FocusCostRecord) GetBillingPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.BillingPeriodEnd
	}
	return nil
}

func (x *FocusCostRecord) GetBillingCurrency() string {
	if x != nil {
		return x.BillingCurrency
	}
	return ""
}

func (x *FocusCostRecord) GetChargePeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.ChargePeriodStart
	}
	return nil
}

func (x *FocusCostRecord) GetChargePeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.ChargePeriodEnd
	}
	return nil
}

func (x *FocusCostRecord) GetChargeCategory() FocusChargeCategory {
	if x != nil {
		return x.ChargeCategory
	}
	return FocusChargeCategory_FOCUS_CHARGE_CATEGORY_UNSPECIFIED
}

func (x *FocusCostRecord) GetChargeClass() FocusChargeClass {
	if x != nil {
		return x.ChargeClass
	}
	return FocusChargeClass_FOCUS_CHARGE_CLASS_UNSPECIFIED
}

func (x *FocusCostRecord) GetChargeDescription() string {
	if x != nil {
		return x.ChargeDescription
	}
	return ""
}

func (x *FocusCostRecord) GetChargeFrequency() FocusChargeFrequency {
	if x != nil {
		return x.ChargeFrequency
	}
	return FocusChargeFrequency_FOCUS_CHARGE_FREQUENCY_UNSPECIFIED
}

func (x *FocusCostRecord) GetPricingCategory() FocusPricingCategory {
	if x != nil {
		return x.PricingCategory
	}
	return FocusPricingCategory_FOCUS_PRICING_CATEGORY_UNSPECIFIED
}

func (x *FocusCostRecord) GetPricingQuantity() float64 {
	if x != nil {
		return x.PricingQuantity
	}
	return 0
}

func (x *FocusCostRecord) GetPricingUnit() string {
	if x != nil {
		return x.PricingUnit
	}
	return ""
}

func (x *FocusCostRecord) GetListUnitPrice() float64 {
	if x != nil {
		return x.ListUnitPrice
	}
	return 0
}

func (x *FocusCostRecord) GetPricingCurrency() string {
	if x != nil {
		return x.PricingCurrency
	}
	return ""
}

func (x *FocusCostRecord) GetPricingCurrencyContractedUnitPrice() float64 {
	if x != nil {
		return x.PricingCurrencyContractedUnitPrice
	}
	return 0
}

func (x *FocusCostRecord) GetPricingCurrencyEffectiveCost() float64 {
	if x != nil {
		return x.PricingCurrencyEffectiveCost
	}
	return 0
}

func (x *FocusCostRecord) GetPricingCurrencyListUnitPrice() float64 {
	if x != nil {
		return x.PricingCurrencyListUnitPrice
	}
	return 0
}

func (x *FocusCostRecord) GetServiceCategory() FocusServiceCategory {
	if x != nil {
		return x.ServiceCategory
	}
	return FocusServiceCategory_FOCUS_SERVICE_CATEGORY_UNSPECIFIED
}

func (x *FocusCostRecord) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *FocusCostRecord) GetServiceSubcategory() string {
	if x != nil {
		return x.ServiceSubcategory
	}
	return ""
}

// Deprecated: Marked as deprecated in pulumicost/v1/focus.proto.
func (x *FocusCostRecord) GetPublisher() string {
	if x != nil {
		return x.Publisher
	}
	return ""
}

func (x *FocusCostRecord) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *FocusCostRecord) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *FocusCostRecord) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *FocusCostRecord) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

func (x *FocusCostRecord) GetSkuPriceId() string {
	if x != nil {
		return x.SkuPriceId
	}
	return ""
}

func (x *FocusCostRecord) GetSkuMeter() string {
	if x != nil {
		return x.SkuMeter
	}
	return ""
}

func (x *FocusCostRecord) GetSkuPriceDetails() string {
	if x != nil {
		return x.SkuPriceDetails
	}
	return ""
}

func (x *FocusCostRecord) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

func (x *FocusCostRecord) GetRegionName() string {
	if x != nil {
		return x.RegionName
	}
	return ""
}

func (x *FocusCostRecord) GetAvailabilityZone() string {
	if x != nil {
		return x.AvailabilityZone
	}
	return ""
}

func (x *FocusCostRecord) GetBilledCost() float64 {
	if x != nil {
		return x.BilledCost
	}
	return 0
}

func (x *FocusCostRecord) GetListCost() float64 {
	if x != nil {
		return x.ListCost
	}
	return 0
}

func (x *FocusCostRecord) GetEffectiveCost() float64 {
	if x != nil {
		return x.EffectiveCost
	}
	return 0
}

func (x *FocusCostRecord) GetContractedCost() float64 {
	if x != nil {
		return x.ContractedCost
	}
	return 0
}

func (x *FocusCostRecord) GetContractedUnitPrice() float64 {
	if x != nil {
		return x.ContractedUnitPrice
	}
	return 0
}

func (x *FocusCostRecord) GetConsumedQuantity() float64 {
	if x != nil {
		return x.ConsumedQuantity
	}
	return 0
}

func (x *FocusCostRecord) GetConsumedUnit() string {
	if x != nil {
		return x.ConsumedUnit
	}
	return ""
}

func (x *FocusCostRecord) GetCommitmentDiscountCategory() FocusCommitmentDiscountCategory {
	if x != nil {
		return x.CommitmentDiscountCategory
	}
	return FocusCommitmentDiscountCategory_FOCUS_COMMITMENT_DISCOUNT_CATEGORY_UNSPECIFIED
}

func (x *FocusCostRecord) GetCommitmentDiscountId() string {
	if x != nil {
		return x.CommitmentDiscountId
	}
	return ""
}

func (x *FocusCostRecord) GetCommitmentDiscountName() string {
	if x != nil {
		return x.CommitmentDiscountName
	}
	return ""
}

func (x *FocusCostRecord) GetCommitmentDiscountQuantity() float64 {
	if x != nil {
		return x.CommitmentDiscountQuantity
	}
	return 0
}

func (x *FocusCostRecord) GetCommitmentDiscountStatus() FocusCommitmentDiscountStatus {
	if x != nil {
		return x.CommitmentDiscountStatus
	}
	return FocusCommitmentDiscountStatus_FOCUS_COMMITMENT_DISCOUNT_STATUS_UNSPECIFIED
}

func (x *FocusCostRecord) GetCommitmentDiscountType() string {
	if x != nil {
		return x.CommitmentDiscountType
	}
	return ""
}

func (x *FocusCostRecord) GetCommitmentDiscountUnit() string {
	if x != nil {
		return x.CommitmentDiscountUnit
	}
	return ""
}

func (x *FocusCostRecord) GetCapacityReservationId() string {
	if x != nil {
		return x.CapacityReservationId
	}
	return ""
}

func (x *FocusCostRecord) GetCapacityReservationStatus() FocusCapacityReservationStatus {
	if x != nil {
		return x.CapacityReservationStatus
	}
	return FocusCapacityReservationStatus_FOCUS_CAPACITY_RESERVATION_STATUS_UNSPECIFIED
}

func (x *FocusCostRecord) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *FocusCostRecord) GetInvoiceIssuer() string {
	if x != nil {
		return x.InvoiceIssuer
	}
	return ""
}

func (x *FocusCostRecord) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *FocusCostRecord) GetExtendedColumns() map[string]string {
	if x != nil {
		return x.ExtendedColumns
	}
	return nil
}

func (x *FocusCostRecord) GetServiceProviderName() string {
	if x != nil {
		return x.ServiceProviderName
	}
	return ""
}

func (x *FocusCostRecord) GetHostProviderName() string {
	if x != nil {
		return x.HostProviderName
	}
	return ""
}

func (x *FocusCostRecord) GetAllocatedMethodId() string {
	if x != nil {
		return x.AllocatedMethodId
	}
	return ""
}

func (x *FocusCostRecord) GetAllocatedMethodDetails() string {
	if x != nil {
		return x.AllocatedMethodDetails
	}
	return ""
}

func (x *FocusCostRecord) GetAllocatedResourceId() string {
	if x != nil {
		return x.AllocatedResourceId
	}
	return ""
}

func (x *FocusCostRecord) GetAllocatedResourceName() string {
	if x != nil {
		return x.AllocatedResourceName
	}
	return ""
}

func (x *FocusCostRecord) GetAllocatedTags() map[string]string {
	if x != nil {
		return x.AllocatedTags
	}
	return nil
}

func (x *FocusCostRecord) GetContractApplied() string {
	if x != nil {
		return x.ContractApplied
	}
	return ""
}

// ContractCommitment represents a contractual commitment record in the
// FOCUS 1.3 Contract Commitment supplemental dataset.
//
// This is a separate dataset from Cost and Usage data, allowing practitioners
// to query contract terms independently from individual cost line items.
//
// Reference: FOCUS 1.3 Contract Commitment Dataset
type ContractCommitment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ContractCommitmentId: Unique identifier for this specific commitment.
	// REQUIRED. Primary key for the commitment record.
	// FOCUS 1.3 Section: Contract Commitment ID
	ContractCommitmentId string `protobuf:"bytes,1,opt,name=contract_commitment_id,json=contractCommitmentId,proto3" json:"contract_commitment_id,omitempty"`
	// ContractId: Identifier of the parent contract containing this commitment.
	// REQUIRED. Links to the broader contract agreement.
	// FOCUS 1.3 Section: Contract ID
	ContractId string `protobuf:"bytes,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	// ContractCommitmentCategory: Category of commitment (SPEND or USAGE).
	// FOCUS 1.3 Contract Commitment Category (CONDITIONAL).
	ContractCommitmentCategory FocusContractCommitmentCategory `protobuf:"varint,3,opt,name=contract_commitment_category,json=contractCommitmentCategory,proto3,enum=pulumicost.v1.FocusContractCommitmentCategory" json:"contract_commitment_category,omitempty"`
	// ContractCommitmentType: Provider-specific type of commitment.
	// Free-form string (e.g., "Reserved Instance", "Savings Plan", "CUD").
	// FOCUS 1.3 Contract Commitment Type (CONDITIONAL).
	ContractCommitmentType string `protobuf:"bytes,4,opt,name=contract_commitment_type,json=contractCommitmentType,proto3" json:"contract_commitment_type,omitempty"`
	// ContractCommitmentPeriodStart: Start of the commitment period.
	// When the specific commitment obligations begin.
	// FOCUS 1.3 Contract Commitment Period Start (CONDITIONAL).
	ContractCommitmentPeriodStart *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=contract_commitment_period_start,json=contractCommitmentPeriodStart,proto3" json:"contract_commitment_period_start,omitempty"`
	// ContractCommitmentPeriodEnd: End of the commitment period.
	// When the specific commitment obligations end.
	// FOCUS 1.3 Contract Commitment Period End (CONDITIONAL).
	ContractCommitmentPeriodEnd *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=contract_commitment_period_end,json=contractCommitmentPeriodEnd,proto3" json:"contract_commitment_period_end,omitempty"`
	// ContractPeriodStart: Start of the overall contract.
	// When the parent contract agreement begins.
	// FOCUS 1.3 Contract Period Start (CONDITIONAL).
	ContractPeriodStart *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=contract_period_start,json=contractPeriodStart,proto3" json:"contract_period_start,omitempty"`
	// ContractPeriodEnd: End of the overall contract.
	// When the parent contract agreement ends.
	// FOCUS 1.3 Contract Period End (CONDITIONAL).
	ContractPeriodEnd *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=contract_period_end,json=contractPeriodEnd,proto3" json:"contract_period_end,omitempty"`
	// ContractCommitmentCost: Monetary amount of the commitment.
	// For SPEND category, this is the dollar/currency amount committed.
	// FOCUS 1.3 Contract Commitment Cost (CONDITIONAL).
	ContractCommitmentCost float64 `protobuf:"fixed64,9,opt,name=contract_commitment_cost,json=contractCommitmentCost,proto3" json:"contract_commitment_cost,omitempty"`
	// ContractCommitmentQuantity: Quantity amount of the commitment.
	// For USAGE category, this is the unit quantity committed.
	// FOCUS 1.3 Contract Commitment Quantity (CONDITIONAL).
	ContractCommitmentQuantity float64 `protobuf:"fixed64,10,opt,name=contract_commitment_quantity,json=contractCommitmentQuantity,proto3" json:"contract_commitment_quantity,omitempty"`
	// ContractCommitmentUnit: Unit of measure for quantity.
	// Examples: "Hours", "GB", "vCPU-Hours", "Requests".
	// FOCUS 1.3 Contract Commitment Unit (CONDITIONAL).
	ContractCommitmentUnit string `protobuf:"bytes,11,opt,name=contract_commitment_unit,json=contractCommitmentUnit,proto3" json:"contract_commitment_unit,omitempty"`
	// BillingCurrency: ISO 4217 currency code for monetary values.
	// REQUIRED. Format: 3-letter currency code (e.g., "USD", "EUR").
	// FOCUS 1.3 Billing Currency
	BillingCurrency string `protobuf:"bytes,12,opt,name=billing_currency,json=billingCurrency,proto3" json:"billing_currency,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ContractCommitment) Reset() {
	*x = ContractCommitment{}
	mi := &file_pulumicost_v1_focus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractCommitment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractCommitment) ProtoMessage() {}

func (x *ContractCommitment) ProtoReflect() protoreflect.Message {
	mi := &file_pulumicost_v1_focus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractCommitment.ProtoReflect.Descriptor instead.
func (*ContractCommitment) Descriptor() ([]byte, []int) {
	return file_pulumicost_v1_focus_proto_rawDescGZIP(), []int{1}
}

func (x *ContractCommitment) GetContractCommitmentId() string {
	if x != nil {
		return x.ContractCommitmentId
	}
	return ""
}

func (x *ContractCommitment) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *ContractCommitment) GetContractCommitmentCategory() FocusContractCommitmentCategory {
	if x != nil {
		return x.ContractCommitmentCategory
	}
	return FocusContractCommitmentCategory_FOCUS_CONTRACT_COMMITMENT_CATEGORY_UNSPECIFIED
}

func (x *ContractCommitment) GetContractCommitmentType() string {
	if x != nil {
		return x.ContractCommitmentType
	}
	return ""
}

func (x *ContractCommitment) GetContractCommitmentPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.ContractCommitmentPeriodStart
	}
	return nil
}

func (x *ContractCommitment) GetContractCommitmentPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.ContractCommitmentPeriodEnd
	}
	return nil
}

func (x *ContractCommitment) GetContractPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.ContractPeriodStart
	}
	return nil
}

func (x *ContractCommitment) GetContractPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.ContractPeriodEnd
	}
	return nil
}

func (x *ContractCommitment) GetContractCommitmentCost() float64 {
	if x != nil {
		return x.ContractCommitmentCost
	}
	return 0
}

func (x *ContractCommitment) GetContractCommitmentQuantity() float64 {
	if x != nil {
		return x.ContractCommitmentQuantity
	}
	return 0
}

func (x *ContractCommitment) GetContractCommitmentUnit() string {
	if x != nil {
		return x.ContractCommitmentUnit
	}
	return ""
}

func (x *ContractCommitment) GetBillingCurrency() string {
	if x != nil {
		return x.BillingCurrency
	}
	return ""
}

var File_pulumicost_v1_focus_proto protoreflect.FileDescriptor

const file_pulumicost_v1_focus_proto_rawDesc = "" +
	"\n" +
	"\x19pulumicost/v1/focus.proto\x12\rpulumicost.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19pulumicost/v1/enums.proto\"\xbe\x1d\n" +
	"\x0fFocusCostRecord\x12'\n" +
	"\rprovider_name\x18\x01 \x01(\tB\x02\x18\x01R\fproviderName\x12,\n" +
	"\x12billing_account_id\x18\x02 \x01(\tR\x10billingAccountId\x120\n" +
	"\x14billing_account_name\x18\x03 \x01(\tR\x12billingAccountName\x12$\n" +
	"\x0esub_account_id\x18\x18 \x01(\tR\fsubAccountId\x12(\n" +
	"\x10sub_account_name\x18\x19 \x01(\tR\x0esubAccountName\x120\n" +
	"\x14billing_account_type\x18* \x01(\tR\x12billingAccountType\x12(\n" +
	"\x10sub_account_type\x18+ \x01(\tR\x0esubAccountType\x12L\n" +
	"\x14billing_period_start\x18\x1a \x01(\v2\x1a.google.protobuf.TimestampR\x12billingPeriodStart\x12H\n" +
	"\x12billing_period_end\x18\x1b \x01(\v2\x1a.google.protobuf.TimestampR\x10billingPeriodEnd\x12)\n" +
	"\x10billing_currency\x18\x12 \x01(\tR\x0fbillingCurrency\x12J\n" +
	"\x13charge_period_start\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x11chargePeriodStart\x12F\n" +
	"\x11charge_period_end\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0fchargePeriodEnd\x12K\n" +
	"\x0fcharge_category\x18\b \x01(\x0e2\".pulumicost.v1.FocusChargeCategoryR\x0echargeCategory\x12B\n" +
	"\fcharge_class\x18\x1c \x01(\x0e2\x1f.pulumicost.v1.FocusChargeClassR\vchargeClass\x12-\n" +
	"\x12charge_description\x18\x1d \x01(\tR\x11chargeDescription\x12N\n" +
	"\x10charge_frequency\x18\x1e \x01(\x0e2#.pulumicost.v1.FocusChargeFrequencyR\x0fchargeFrequency\x12N\n" +
	"\x10pricing_category\x18\t \x01(\x0e2#.pulumicost.v1.FocusPricingCategoryR\x0fpricingCategory\x12)\n" +
	"\x10pricing_quantity\x18\x1f \x01(\x01R\x0fpricingQuantity\x12!\n" +
	"\fpricing_unit\x18  \x01(\tR\vpricingUnit\x12&\n" +
	"\x0flist_unit_price\x18! \x01(\x01R\rlistUnitPrice\x12)\n" +
	"\x10pricing_currency\x183 \x01(\tR\x0fpricingCurrency\x12R\n" +
	"&pricing_currency_contracted_unit_price\x184 \x01(\x01R\"pricingCurrencyContractedUnitPrice\x12E\n" +
	"\x1fpricing_currency_effective_cost\x185 \x01(\x01R\x1cpricingCurrencyEffectiveCost\x12F\n" +
	" pricing_currency_list_unit_price\x186 \x01(\x01R\x1cpricingCurrencyListUnitPrice\x12N\n" +
	"\x10service_category\x18\x06 \x01(\x0e2#.pulumicost.v1.FocusServiceCategoryR\x0fserviceCategory\x12!\n" +
	"\fservice_name\x18\a \x01(\tR\vserviceName\x12/\n" +
	"\x13service_subcategory\x188 \x01(\tR\x12serviceSubcategory\x12 \n" +
	"\tpublisher\x187 \x01(\tB\x02\x18\x01R\tpublisher\x12\x1f\n" +
	"\vresource_id\x18\f \x01(\tR\n" +
	"resourceId\x12#\n" +
	"\rresource_name\x18\r \x01(\tR\fresourceName\x12#\n" +
	"\rresource_type\x18\" \x01(\tR\fresourceType\x12\x15\n" +
	"\x06sku_id\x18\x0e \x01(\tR\x05skuId\x12 \n" +
	"\fsku_price_id\x18# \x01(\tR\n" +
	"skuPriceId\x12\x1b\n" +
	"\tsku_meter\x189 \x01(\tR\bskuMeter\x12*\n" +
	"\x11sku_price_details\x18: \x01(\tR\x0fskuPriceDetails\x12\x1b\n" +
	"\tregion_id\x18\n" +
	" \x01(\tR\bregionId\x12\x1f\n" +
	"\vregion_name\x18\v \x01(\tR\n" +
	"regionName\x12+\n" +
	"\x11availability_zone\x18$ \x01(\tR\x10availabilityZone\x12\x1f\n" +
	"\vbilled_cost\x18\x0f \x01(\x01R\n" +
	"billedCost\x12\x1b\n" +
	"\tlist_cost\x18\x10 \x01(\x01R\blistCost\x12%\n" +
	"\x0eeffective_cost\x18\x11 \x01(\x01R\reffectiveCost\x12'\n" +
	"\x0fcontracted_cost\x18) \x01(\x01R\x0econtractedCost\x122\n" +
	"\x15contracted_unit_price\x182 \x01(\x01R\x13contractedUnitPrice\x12+\n" +
	"\x11consumed_quantity\x18\x14 \x01(\x01R\x10consumedQuantity\x12#\n" +
	"\rconsumed_unit\x18\x15 \x01(\tR\fconsumedUnit\x12p\n" +
	"\x1ccommitment_discount_category\x18% \x01(\x0e2..pulumicost.v1.FocusCommitmentDiscountCategoryR\x1acommitmentDiscountCategory\x124\n" +
	"\x16commitment_discount_id\x18& \x01(\tR\x14commitmentDiscountId\x128\n" +
	"\x18commitment_discount_name\x18' \x01(\tR\x16commitmentDiscountName\x12@\n" +
	"\x1ccommitment_discount_quantity\x18. \x01(\x01R\x1acommitmentDiscountQuantity\x12j\n" +
	"\x1acommitment_discount_status\x18/ \x01(\x0e2,.pulumicost.v1.FocusCommitmentDiscountStatusR\x18commitmentDiscountStatus\x128\n" +
	"\x18commitment_discount_type\x180 \x01(\tR\x16commitmentDiscountType\x128\n" +
	"\x18commitment_discount_unit\x181 \x01(\tR\x16commitmentDiscountUnit\x126\n" +
	"\x17capacity_reservation_id\x18, \x01(\tR\x15capacityReservationId\x12m\n" +
	"\x1bcapacity_reservation_status\x18- \x01(\x0e2-.pulumicost.v1.FocusCapacityReservationStatusR\x19capacityReservationStatus\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x13 \x01(\tR\tinvoiceId\x12%\n" +
	"\x0einvoice_issuer\x18( \x01(\tR\rinvoiceIssuer\x12<\n" +
	"\x04tags\x18\x16 \x03(\v2(.pulumicost.v1.FocusCostRecord.TagsEntryR\x04tags\x12^\n" +
	"\x10extended_columns\x18\x17 \x03(\v23.pulumicost.v1.FocusCostRecord.ExtendedColumnsEntryR\x0fextendedColumns\x122\n" +
	"\x15service_provider_name\x18; \x01(\tR\x13serviceProviderName\x12,\n" +
	"\x12host_provider_name\x18< \x01(\tR\x10hostProviderName\x12.\n" +
	"\x13allocated_method_id\x18= \x01(\tR\x11allocatedMethodId\x128\n" +
	"\x18allocated_method_details\x18> \x01(\tR\x16allocatedMethodDetails\x122\n" +
	"\x15allocated_resource_id\x18? \x01(\tR\x13allocatedResourceId\x126\n" +
	"\x17allocated_resource_name\x18@ \x01(\tR\x15allocatedResourceName\x12X\n" +
	"\x0eallocated_tags\x18A \x03(\v21.pulumicost.v1.FocusCostRecord.AllocatedTagsEntryR\rallocatedTags\x12)\n" +
	"\x10contract_applied\x18B \x01(\tR\x0fcontractApplied\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14ExtendedColumnsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a@\n" +
	"\x12AllocatedTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xda\x06\n" +
	"\x12ContractCommitment\x124\n" +
	"\x16contract_commitment_id\x18\x01 \x01(\tR\x14contractCommitmentId\x12\x1f\n" +
	"\vcontract_id\x18\x02 \x01(\tR\n" +
	"contractId\x12p\n" +
	"\x1ccontract_commitment_category\x18\x03 \x01(\x0e2..pulumicost.v1.FocusContractCommitmentCategoryR\x1acontractCommitmentCategory\x128\n" +
	"\x18contract_commitment_type\x18\x04 \x01(\tR\x16contractCommitmentType\x12c\n" +
	" contract_commitment_period_start\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x1dcontractCommitmentPeriodStart\x12_\n" +
	"\x1econtract_commitment_period_end\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x1bcontractCommitmentPeriodEnd\x12N\n" +
	"\x15contract_period_start\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x13contractPeriodStart\x12J\n" +
	"\x13contract_period_end\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x11contractPeriodEnd\x128\n" +
	"\x18contract_commitment_cost\x18\t \x01(\x01R\x16contractCommitmentCost\x12@\n" +
	"\x1ccontract_commitment_quantity\x18\n" +
	" \x01(\x01R\x1acontractCommitmentQuantity\x128\n" +
	"\x18contract_commitment_unit\x18\v \x01(\tR\x16contractCommitmentUnit\x12)\n" +
	"\x10billing_currency\x18\f \x01(\tR\x0fbillingCurrency*\xb1\x01\n" +
	"\x1fFocusContractCommitmentCategory\x122\n" +
	".FOCUS_CONTRACT_COMMITMENT_CATEGORY_UNSPECIFIED\x10\x00\x12,\n" +
	"(FOCUS_CONTRACT_COMMITMENT_CATEGORY_SPEND\x10\x01\x12,\n" +
	"(FOCUS_CONTRACT_COMMITMENT_CATEGORY_USAGE\x10\x02B4Z2github.com/rshade/pulumicost-spec/sdk/go/proto;pbcb\x06proto3"

var (
	file_pulumicost_v1_focus_proto_rawDescOnce sync.Once
	file_pulumicost_v1_focus_proto_rawDescData []byte
)

func file_pulumicost_v1_focus_proto_rawDescGZIP() []byte {
	file_pulumicost_v1_focus_proto_rawDescOnce.Do(func() {
		file_pulumicost_v1_focus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pulumicost_v1_focus_proto_rawDesc), len(file_pulumicost_v1_focus_proto_rawDesc)))
	})
	return file_pulumicost_v1_focus_proto_rawDescData
}

var file_pulumicost_v1_focus_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pulumicost_v1_focus_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pulumicost_v1_focus_proto_goTypes = []any{
	(FocusContractCommitmentCategory)(0), // 0: pulumicost.v1.FocusContractCommitmentCategory
	(*FocusCostRecord)(nil),              // 1: pulumicost.v1.FocusCostRecord
	(*ContractCommitment)(nil),           // 2: pulumicost.v1.ContractCommitment
	nil,                                  // 3: pulumicost.v1.FocusCostRecord.TagsEntry
	nil,                                  // 4: pulumicost.v1.FocusCostRecord.ExtendedColumnsEntry
	nil,                                  // 5: pulumicost.v1.FocusCostRecord.AllocatedTagsEntry
	(*timestamppb.Timestamp)(nil),        // 6: google.protobuf.Timestamp
	(FocusChargeCategory)(0),             // 7: pulumicost.v1.FocusChargeCategory
	(FocusChargeClass)(0),                // 8: pulumicost.v1.FocusChargeClass
	(FocusChargeFrequency)(0),            // 9: pulumicost.v1.FocusChargeFrequency
	(FocusPricingCategory)(0),            // 10: pulumicost.v1.FocusPricingCategory
	(FocusServiceCategory)(0),            // 11: pulumicost.v1.FocusServiceCategory
	(FocusCommitmentDiscountCategory)(0), // 12: pulumicost.v1.FocusCommitmentDiscountCategory
	(FocusCommitmentDiscountStatus)(0),   // 13: pulumicost.v1.FocusCommitmentDiscountStatus
	(FocusCapacityReservationStatus)(0),  // 14: pulumicost.v1.FocusCapacityReservationStatus
}
var file_pulumicost_v1_focus_proto_depIdxs = []int32{
	6,  // 0: pulumicost.v1.FocusCostRecord.billing_period_start:type_name -> google.protobuf.Timestamp
	6,  // 1: pulumicost.v1.FocusCostRecord.billing_period_end:type_name -> google.protobuf.Timestamp
	6,  // 2: pulumicost.v1.FocusCostRecord.charge_period_start:type_name -> google.protobuf.Timestamp
	6,  // 3: pulumicost.v1.FocusCostRecord.charge_period_end:type_name -> google.protobuf.Timestamp
	7,  // 4: pulumicost.v1.FocusCostRecord.charge_category:type_name -> pulumicost.v1.FocusChargeCategory
	8,  // 5: pulumicost.v1.FocusCostRecord.charge_class:type_name -> pulumicost.v1.FocusChargeClass
	9,  // 6: pulumicost.v1.FocusCostRecord.charge_frequency:type_name -> pulumicost.v1.FocusChargeFrequency
	10, // 7: pulumicost.v1.FocusCostRecord.pricing_category:type_name -> pulumicost.v1.FocusPricingCategory
	11, // 8: pulumicost.v1.FocusCostRecord.service_category:type_name -> pulumicost.v1.FocusServiceCategory
	12, // 9: pulumicost.v1.FocusCostRecord.commitment_discount_category:type_name -> pulumicost.v1.FocusCommitmentDiscountCategory
	13, // 10: pulumicost.v1.FocusCostRecord.commitment_discount_status:type_name -> pulumicost.v1.FocusCommitmentDiscountStatus
	14, // 11: pulumicost.v1.FocusCostRecord.capacity_reservation_status:type_name -> pulumicost.v1.FocusCapacityReservationStatus
	3,  // 12: pulumicost.v1.FocusCostRecord.tags:type_name -> pulumicost.v1.FocusCostRecord.TagsEntry
	4,  // 13: pulumicost.v1.FocusCostRecord.extended_columns:type_name -> pulumicost.v1.FocusCostRecord.ExtendedColumnsEntry
	5,  // 14: pulumicost.v1.FocusCostRecord.allocated_tags:type_name -> pulumicost.v1.FocusCostRecord.AllocatedTagsEntry
	0,  // 15: pulumicost.v1.ContractCommitment.contract_commitment_category:type_name -> pulumicost.v1.FocusContractCommitmentCategory
	6,  // 16: pulumicost.v1.ContractCommitment.contract_commitment_period_start:type_name -> google.protobuf.Timestamp
	6,  // 17: pulumicost.v1.ContractCommitment.contract_commitment_period_end:type_name -> google.protobuf.Timestamp
	6,  // 18: pulumicost.v1.ContractCommitment.contract_period_start:type_name -> google.protobuf.Timestamp
	6,  // 19: pulumicost.v1.ContractCommitment.contract_period_end:type_name -> google.protobuf.Timestamp
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_pulumicost_v1_focus_proto_init() }
func file_pulumicost_v1_focus_proto_init() {
	if File_pulumicost_v1_focus_proto != nil {
		return
	}
	file_pulumicost_v1_enums_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pulumicost_v1_focus_proto_rawDesc), len(file_pulumicost_v1_focus_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pulumicost_v1_focus_proto_goTypes,
		DependencyIndexes: file_pulumicost_v1_focus_proto_depIdxs,
		EnumInfos:         file_pulumicost_v1_focus_proto_enumTypes,
		MessageInfos:      file_pulumicost_v1_focus_proto_msgTypes,
	}.Build()
	File_pulumicost_v1_focus_proto = out.File
	file_pulumicost_v1_focus_proto_goTypes = nil
	file_pulumicost_v1_focus_proto_depIdxs = nil
}
