// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: finfocus/v1/registry.proto

package pbcconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/rshade/finfocus-spec/sdk/go/proto/finfocus/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PluginRegistryServiceName is the fully-qualified name of the PluginRegistryService service.
	PluginRegistryServiceName = "finfocus.v1.PluginRegistryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PluginRegistryServiceDiscoverPluginsProcedure is the fully-qualified name of the
	// PluginRegistryService's DiscoverPlugins RPC.
	PluginRegistryServiceDiscoverPluginsProcedure = "/finfocus.v1.PluginRegistryService/DiscoverPlugins"
	// PluginRegistryServiceGetPluginManifestProcedure is the fully-qualified name of the
	// PluginRegistryService's GetPluginManifest RPC.
	PluginRegistryServiceGetPluginManifestProcedure = "/finfocus.v1.PluginRegistryService/GetPluginManifest"
	// PluginRegistryServiceValidatePluginProcedure is the fully-qualified name of the
	// PluginRegistryService's ValidatePlugin RPC.
	PluginRegistryServiceValidatePluginProcedure = "/finfocus.v1.PluginRegistryService/ValidatePlugin"
	// PluginRegistryServiceInstallPluginProcedure is the fully-qualified name of the
	// PluginRegistryService's InstallPlugin RPC.
	PluginRegistryServiceInstallPluginProcedure = "/finfocus.v1.PluginRegistryService/InstallPlugin"
	// PluginRegistryServiceUpdatePluginProcedure is the fully-qualified name of the
	// PluginRegistryService's UpdatePlugin RPC.
	PluginRegistryServiceUpdatePluginProcedure = "/finfocus.v1.PluginRegistryService/UpdatePlugin"
	// PluginRegistryServiceRemovePluginProcedure is the fully-qualified name of the
	// PluginRegistryService's RemovePlugin RPC.
	PluginRegistryServiceRemovePluginProcedure = "/finfocus.v1.PluginRegistryService/RemovePlugin"
	// PluginRegistryServiceListInstalledPluginsProcedure is the fully-qualified name of the
	// PluginRegistryService's ListInstalledPlugins RPC.
	PluginRegistryServiceListInstalledPluginsProcedure = "/finfocus.v1.PluginRegistryService/ListInstalledPlugins"
	// PluginRegistryServiceCheckPluginHealthProcedure is the fully-qualified name of the
	// PluginRegistryService's CheckPluginHealth RPC.
	PluginRegistryServiceCheckPluginHealthProcedure = "/finfocus.v1.PluginRegistryService/CheckPluginHealth"
)

// PluginRegistryServiceClient is a client for the finfocus.v1.PluginRegistryService service.
type PluginRegistryServiceClient interface {
	// DiscoverPlugins discovers available plugins from configured sources.
	DiscoverPlugins(context.Context, *connect.Request[v1.DiscoverPluginsRequest]) (*connect.Response[v1.DiscoverPluginsResponse], error)
	// GetPluginManifest retrieves the manifest for a specific plugin.
	GetPluginManifest(context.Context, *connect.Request[v1.GetPluginManifestRequest]) (*connect.Response[v1.GetPluginManifestResponse], error)
	// ValidatePlugin validates a plugin's manifest and dependencies.
	ValidatePlugin(context.Context, *connect.Request[v1.ValidatePluginRequest]) (*connect.Response[v1.ValidatePluginResponse], error)
	// InstallPlugin installs a plugin from a specified source.
	InstallPlugin(context.Context, *connect.Request[v1.InstallPluginRequest]) (*connect.Response[v1.InstallPluginResponse], error)
	// UpdatePlugin updates an existing plugin to a new version.
	UpdatePlugin(context.Context, *connect.Request[v1.UpdatePluginRequest]) (*connect.Response[v1.UpdatePluginResponse], error)
	// RemovePlugin removes an installed plugin.
	RemovePlugin(context.Context, *connect.Request[v1.RemovePluginRequest]) (*connect.Response[v1.RemovePluginResponse], error)
	// ListInstalledPlugins lists all currently installed plugins.
	ListInstalledPlugins(context.Context, *connect.Request[v1.ListInstalledPluginsRequest]) (*connect.Response[v1.ListInstalledPluginsResponse], error)
	// CheckPluginHealth verifies plugin health and connectivity.
	CheckPluginHealth(context.Context, *connect.Request[v1.CheckPluginHealthRequest]) (*connect.Response[v1.CheckPluginHealthResponse], error)
}

// NewPluginRegistryServiceClient constructs a client for the finfocus.v1.PluginRegistryService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPluginRegistryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PluginRegistryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	pluginRegistryServiceMethods := v1.File_finfocus_v1_registry_proto.Services().ByName("PluginRegistryService").Methods()
	return &pluginRegistryServiceClient{
		discoverPlugins: connect.NewClient[v1.DiscoverPluginsRequest, v1.DiscoverPluginsResponse](
			httpClient,
			baseURL+PluginRegistryServiceDiscoverPluginsProcedure,
			connect.WithSchema(pluginRegistryServiceMethods.ByName("DiscoverPlugins")),
			connect.WithClientOptions(opts...),
		),
		getPluginManifest: connect.NewClient[v1.GetPluginManifestRequest, v1.GetPluginManifestResponse](
			httpClient,
			baseURL+PluginRegistryServiceGetPluginManifestProcedure,
			connect.WithSchema(pluginRegistryServiceMethods.ByName("GetPluginManifest")),
			connect.WithClientOptions(opts...),
		),
		validatePlugin: connect.NewClient[v1.ValidatePluginRequest, v1.ValidatePluginResponse](
			httpClient,
			baseURL+PluginRegistryServiceValidatePluginProcedure,
			connect.WithSchema(pluginRegistryServiceMethods.ByName("ValidatePlugin")),
			connect.WithClientOptions(opts...),
		),
		installPlugin: connect.NewClient[v1.InstallPluginRequest, v1.InstallPluginResponse](
			httpClient,
			baseURL+PluginRegistryServiceInstallPluginProcedure,
			connect.WithSchema(pluginRegistryServiceMethods.ByName("InstallPlugin")),
			connect.WithClientOptions(opts...),
		),
		updatePlugin: connect.NewClient[v1.UpdatePluginRequest, v1.UpdatePluginResponse](
			httpClient,
			baseURL+PluginRegistryServiceUpdatePluginProcedure,
			connect.WithSchema(pluginRegistryServiceMethods.ByName("UpdatePlugin")),
			connect.WithClientOptions(opts...),
		),
		removePlugin: connect.NewClient[v1.RemovePluginRequest, v1.RemovePluginResponse](
			httpClient,
			baseURL+PluginRegistryServiceRemovePluginProcedure,
			connect.WithSchema(pluginRegistryServiceMethods.ByName("RemovePlugin")),
			connect.WithClientOptions(opts...),
		),
		listInstalledPlugins: connect.NewClient[v1.ListInstalledPluginsRequest, v1.ListInstalledPluginsResponse](
			httpClient,
			baseURL+PluginRegistryServiceListInstalledPluginsProcedure,
			connect.WithSchema(pluginRegistryServiceMethods.ByName("ListInstalledPlugins")),
			connect.WithClientOptions(opts...),
		),
		checkPluginHealth: connect.NewClient[v1.CheckPluginHealthRequest, v1.CheckPluginHealthResponse](
			httpClient,
			baseURL+PluginRegistryServiceCheckPluginHealthProcedure,
			connect.WithSchema(pluginRegistryServiceMethods.ByName("CheckPluginHealth")),
			connect.WithClientOptions(opts...),
		),
	}
}

// pluginRegistryServiceClient implements PluginRegistryServiceClient.
type pluginRegistryServiceClient struct {
	discoverPlugins      *connect.Client[v1.DiscoverPluginsRequest, v1.DiscoverPluginsResponse]
	getPluginManifest    *connect.Client[v1.GetPluginManifestRequest, v1.GetPluginManifestResponse]
	validatePlugin       *connect.Client[v1.ValidatePluginRequest, v1.ValidatePluginResponse]
	installPlugin        *connect.Client[v1.InstallPluginRequest, v1.InstallPluginResponse]
	updatePlugin         *connect.Client[v1.UpdatePluginRequest, v1.UpdatePluginResponse]
	removePlugin         *connect.Client[v1.RemovePluginRequest, v1.RemovePluginResponse]
	listInstalledPlugins *connect.Client[v1.ListInstalledPluginsRequest, v1.ListInstalledPluginsResponse]
	checkPluginHealth    *connect.Client[v1.CheckPluginHealthRequest, v1.CheckPluginHealthResponse]
}

// DiscoverPlugins calls finfocus.v1.PluginRegistryService.DiscoverPlugins.
func (c *pluginRegistryServiceClient) DiscoverPlugins(ctx context.Context, req *connect.Request[v1.DiscoverPluginsRequest]) (*connect.Response[v1.DiscoverPluginsResponse], error) {
	return c.discoverPlugins.CallUnary(ctx, req)
}

// GetPluginManifest calls finfocus.v1.PluginRegistryService.GetPluginManifest.
func (c *pluginRegistryServiceClient) GetPluginManifest(ctx context.Context, req *connect.Request[v1.GetPluginManifestRequest]) (*connect.Response[v1.GetPluginManifestResponse], error) {
	return c.getPluginManifest.CallUnary(ctx, req)
}

// ValidatePlugin calls finfocus.v1.PluginRegistryService.ValidatePlugin.
func (c *pluginRegistryServiceClient) ValidatePlugin(ctx context.Context, req *connect.Request[v1.ValidatePluginRequest]) (*connect.Response[v1.ValidatePluginResponse], error) {
	return c.validatePlugin.CallUnary(ctx, req)
}

// InstallPlugin calls finfocus.v1.PluginRegistryService.InstallPlugin.
func (c *pluginRegistryServiceClient) InstallPlugin(ctx context.Context, req *connect.Request[v1.InstallPluginRequest]) (*connect.Response[v1.InstallPluginResponse], error) {
	return c.installPlugin.CallUnary(ctx, req)
}

// UpdatePlugin calls finfocus.v1.PluginRegistryService.UpdatePlugin.
func (c *pluginRegistryServiceClient) UpdatePlugin(ctx context.Context, req *connect.Request[v1.UpdatePluginRequest]) (*connect.Response[v1.UpdatePluginResponse], error) {
	return c.updatePlugin.CallUnary(ctx, req)
}

// RemovePlugin calls finfocus.v1.PluginRegistryService.RemovePlugin.
func (c *pluginRegistryServiceClient) RemovePlugin(ctx context.Context, req *connect.Request[v1.RemovePluginRequest]) (*connect.Response[v1.RemovePluginResponse], error) {
	return c.removePlugin.CallUnary(ctx, req)
}

// ListInstalledPlugins calls finfocus.v1.PluginRegistryService.ListInstalledPlugins.
func (c *pluginRegistryServiceClient) ListInstalledPlugins(ctx context.Context, req *connect.Request[v1.ListInstalledPluginsRequest]) (*connect.Response[v1.ListInstalledPluginsResponse], error) {
	return c.listInstalledPlugins.CallUnary(ctx, req)
}

// CheckPluginHealth calls finfocus.v1.PluginRegistryService.CheckPluginHealth.
func (c *pluginRegistryServiceClient) CheckPluginHealth(ctx context.Context, req *connect.Request[v1.CheckPluginHealthRequest]) (*connect.Response[v1.CheckPluginHealthResponse], error) {
	return c.checkPluginHealth.CallUnary(ctx, req)
}

// PluginRegistryServiceHandler is an implementation of the finfocus.v1.PluginRegistryService
// service.
type PluginRegistryServiceHandler interface {
	// DiscoverPlugins discovers available plugins from configured sources.
	DiscoverPlugins(context.Context, *connect.Request[v1.DiscoverPluginsRequest]) (*connect.Response[v1.DiscoverPluginsResponse], error)
	// GetPluginManifest retrieves the manifest for a specific plugin.
	GetPluginManifest(context.Context, *connect.Request[v1.GetPluginManifestRequest]) (*connect.Response[v1.GetPluginManifestResponse], error)
	// ValidatePlugin validates a plugin's manifest and dependencies.
	ValidatePlugin(context.Context, *connect.Request[v1.ValidatePluginRequest]) (*connect.Response[v1.ValidatePluginResponse], error)
	// InstallPlugin installs a plugin from a specified source.
	InstallPlugin(context.Context, *connect.Request[v1.InstallPluginRequest]) (*connect.Response[v1.InstallPluginResponse], error)
	// UpdatePlugin updates an existing plugin to a new version.
	UpdatePlugin(context.Context, *connect.Request[v1.UpdatePluginRequest]) (*connect.Response[v1.UpdatePluginResponse], error)
	// RemovePlugin removes an installed plugin.
	RemovePlugin(context.Context, *connect.Request[v1.RemovePluginRequest]) (*connect.Response[v1.RemovePluginResponse], error)
	// ListInstalledPlugins lists all currently installed plugins.
	ListInstalledPlugins(context.Context, *connect.Request[v1.ListInstalledPluginsRequest]) (*connect.Response[v1.ListInstalledPluginsResponse], error)
	// CheckPluginHealth verifies plugin health and connectivity.
	CheckPluginHealth(context.Context, *connect.Request[v1.CheckPluginHealthRequest]) (*connect.Response[v1.CheckPluginHealthResponse], error)
}

// NewPluginRegistryServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPluginRegistryServiceHandler(svc PluginRegistryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	pluginRegistryServiceMethods := v1.File_finfocus_v1_registry_proto.Services().ByName("PluginRegistryService").Methods()
	pluginRegistryServiceDiscoverPluginsHandler := connect.NewUnaryHandler(
		PluginRegistryServiceDiscoverPluginsProcedure,
		svc.DiscoverPlugins,
		connect.WithSchema(pluginRegistryServiceMethods.ByName("DiscoverPlugins")),
		connect.WithHandlerOptions(opts...),
	)
	pluginRegistryServiceGetPluginManifestHandler := connect.NewUnaryHandler(
		PluginRegistryServiceGetPluginManifestProcedure,
		svc.GetPluginManifest,
		connect.WithSchema(pluginRegistryServiceMethods.ByName("GetPluginManifest")),
		connect.WithHandlerOptions(opts...),
	)
	pluginRegistryServiceValidatePluginHandler := connect.NewUnaryHandler(
		PluginRegistryServiceValidatePluginProcedure,
		svc.ValidatePlugin,
		connect.WithSchema(pluginRegistryServiceMethods.ByName("ValidatePlugin")),
		connect.WithHandlerOptions(opts...),
	)
	pluginRegistryServiceInstallPluginHandler := connect.NewUnaryHandler(
		PluginRegistryServiceInstallPluginProcedure,
		svc.InstallPlugin,
		connect.WithSchema(pluginRegistryServiceMethods.ByName("InstallPlugin")),
		connect.WithHandlerOptions(opts...),
	)
	pluginRegistryServiceUpdatePluginHandler := connect.NewUnaryHandler(
		PluginRegistryServiceUpdatePluginProcedure,
		svc.UpdatePlugin,
		connect.WithSchema(pluginRegistryServiceMethods.ByName("UpdatePlugin")),
		connect.WithHandlerOptions(opts...),
	)
	pluginRegistryServiceRemovePluginHandler := connect.NewUnaryHandler(
		PluginRegistryServiceRemovePluginProcedure,
		svc.RemovePlugin,
		connect.WithSchema(pluginRegistryServiceMethods.ByName("RemovePlugin")),
		connect.WithHandlerOptions(opts...),
	)
	pluginRegistryServiceListInstalledPluginsHandler := connect.NewUnaryHandler(
		PluginRegistryServiceListInstalledPluginsProcedure,
		svc.ListInstalledPlugins,
		connect.WithSchema(pluginRegistryServiceMethods.ByName("ListInstalledPlugins")),
		connect.WithHandlerOptions(opts...),
	)
	pluginRegistryServiceCheckPluginHealthHandler := connect.NewUnaryHandler(
		PluginRegistryServiceCheckPluginHealthProcedure,
		svc.CheckPluginHealth,
		connect.WithSchema(pluginRegistryServiceMethods.ByName("CheckPluginHealth")),
		connect.WithHandlerOptions(opts...),
	)
	return "/finfocus.v1.PluginRegistryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PluginRegistryServiceDiscoverPluginsProcedure:
			pluginRegistryServiceDiscoverPluginsHandler.ServeHTTP(w, r)
		case PluginRegistryServiceGetPluginManifestProcedure:
			pluginRegistryServiceGetPluginManifestHandler.ServeHTTP(w, r)
		case PluginRegistryServiceValidatePluginProcedure:
			pluginRegistryServiceValidatePluginHandler.ServeHTTP(w, r)
		case PluginRegistryServiceInstallPluginProcedure:
			pluginRegistryServiceInstallPluginHandler.ServeHTTP(w, r)
		case PluginRegistryServiceUpdatePluginProcedure:
			pluginRegistryServiceUpdatePluginHandler.ServeHTTP(w, r)
		case PluginRegistryServiceRemovePluginProcedure:
			pluginRegistryServiceRemovePluginHandler.ServeHTTP(w, r)
		case PluginRegistryServiceListInstalledPluginsProcedure:
			pluginRegistryServiceListInstalledPluginsHandler.ServeHTTP(w, r)
		case PluginRegistryServiceCheckPluginHealthProcedure:
			pluginRegistryServiceCheckPluginHealthHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPluginRegistryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPluginRegistryServiceHandler struct{}

func (UnimplementedPluginRegistryServiceHandler) DiscoverPlugins(context.Context, *connect.Request[v1.DiscoverPluginsRequest]) (*connect.Response[v1.DiscoverPluginsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("finfocus.v1.PluginRegistryService.DiscoverPlugins is not implemented"))
}

func (UnimplementedPluginRegistryServiceHandler) GetPluginManifest(context.Context, *connect.Request[v1.GetPluginManifestRequest]) (*connect.Response[v1.GetPluginManifestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("finfocus.v1.PluginRegistryService.GetPluginManifest is not implemented"))
}

func (UnimplementedPluginRegistryServiceHandler) ValidatePlugin(context.Context, *connect.Request[v1.ValidatePluginRequest]) (*connect.Response[v1.ValidatePluginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("finfocus.v1.PluginRegistryService.ValidatePlugin is not implemented"))
}

func (UnimplementedPluginRegistryServiceHandler) InstallPlugin(context.Context, *connect.Request[v1.InstallPluginRequest]) (*connect.Response[v1.InstallPluginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("finfocus.v1.PluginRegistryService.InstallPlugin is not implemented"))
}

func (UnimplementedPluginRegistryServiceHandler) UpdatePlugin(context.Context, *connect.Request[v1.UpdatePluginRequest]) (*connect.Response[v1.UpdatePluginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("finfocus.v1.PluginRegistryService.UpdatePlugin is not implemented"))
}

func (UnimplementedPluginRegistryServiceHandler) RemovePlugin(context.Context, *connect.Request[v1.RemovePluginRequest]) (*connect.Response[v1.RemovePluginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("finfocus.v1.PluginRegistryService.RemovePlugin is not implemented"))
}

func (UnimplementedPluginRegistryServiceHandler) ListInstalledPlugins(context.Context, *connect.Request[v1.ListInstalledPluginsRequest]) (*connect.Response[v1.ListInstalledPluginsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("finfocus.v1.PluginRegistryService.ListInstalledPlugins is not implemented"))
}

func (UnimplementedPluginRegistryServiceHandler) CheckPluginHealth(context.Context, *connect.Request[v1.CheckPluginHealthRequest]) (*connect.Response[v1.CheckPluginHealthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("finfocus.v1.PluginRegistryService.CheckPluginHealth is not implemented"))
}
